### ISSUE TITLE
Events selection gets stuck

### ISSUE THREAD

**Issue by coppolaemilio** [dialogic-godot/dialogic#1003]
After alt-tabbing out of Godot (or some other things, can't reproduce at the moment) the events on the timeline can only be selected and you can't de-select them.

This happens in both 2.0 and 1.4.

It is as if you were pressing `shift` the entire time

On this video the only input I'm using is the left mouse click.

https://user-images.githubusercontent.com/2206700/178734281-072825b6-2218-43c3-96df-76c819a7765a.mp4

**Comment by Yotopihi-Dev** [comment]
This happened to me when I made a custom event and added extra UI (a checkbox)

**Comment by Jowan-Spooner** [comment]
I do think this is outdated at least for 2.x
