### ISSUE TITLE
slide_in_right.gd is a duplicate of back_in_right.gd, and scales incorrectly.

### ISSUE THREAD

**Issue by thetntm** [dialogic-godot/dialogic#1194]
## The problem

**Describe the bug**
slide_in_right.gd contains incorrect code that causes the animation to have a scaling effect it should not have. The code is identical to back_in_right which I believe is intended to have this effect

**To Reproduce**
1. Create a character that enters a scene with the slide_in_right animation
2. build the scene and watch as the animation that plays is incorrect

**Expected behavior**
The character should slide into the scene without scaling at all. 

**System (please complete the following information):**
 - OS: Mac
 - Godot Version: 3.5.stable.official
 - Dialogic Version: 1.4.5

## Solutions

**Workaround**

I removed lines 8-13 and line 24 of the code in addons/dialogic/Nodes/Anima/animations/entrances_and_exits)/slide_in_right.gd

**Possible fixes**

this can be fixed by removing lines 8-13 and line 24 of the code in addons/dialogic/Nodes/Anima/animations/entrances_and_exits)/slide_in_right.gd

**screenshot**
<img width="916" alt="Screen Shot 2022-08-30 at 10 27 26 AM" src="https://user-images.githubusercontent.com/12042483/187477926-fe39eab9-a73c-45ec-8584-a5543ba64fee.png">
here is a screenshot of the edited code

**Comment by coppolaemilio** [comment]
Closing since Dialogic 1 is no longer in active development
