### ISSUE TITLE
Using GLES2, the theme cannot be changed.

### ISSUE THREAD

**Issue by jtbarts2021** [dialogic-godot/dialogic#1212]
Using GLES2 I can't add a theme, the editor can't be displayed, in general I can't modify the default theme.... godot closes spontaneously when I try to enter the theme editor.

**Comment by RiperG2** [comment]
Same problem, when you want to add a new theme or simply want to edit the default theme, Godot stops working.
![image](https://user-images.githubusercontent.com/87088665/194947540-77fdb26b-5a1d-4ae1-a3ea-02c95f74e5b4.png)
