### ISSUE TITLE
Jello animation non-functional on .png portraits

### ISSUE THREAD

**Issue by Bropocalypse** [dialogic-godot/dialogic#1227]
## The problem

**Describe the bug**
All animations in the 'update' character event work for .png portraits except for the one titled 'jello'. The animation is simply skipped.

**To Reproduce**
Using a character with a .png portrait, create a timeline with the character event with the animation set to 'jello'

**Expected behavior**
it should animate as with .tscn portraits.

**Screenshots**
![image](https://user-images.githubusercontent.com/58696984/190537724-9289a3d4-d438-41c0-b9f8-512b7e212b08.png)

**System (please complete the following information):**
 - OS: Kubuntu 20.04
 - Godot 3.5
 - Dialogic 1.4.5

If there's a technical limitation preventing this behavior from functioning, there's no indication of that in the plugin.
One workaround is to use a .tscn instead of a .png, but in some situations that can cause haults #1226

**Comment by coppolaemilio** [comment]
Closing since Dialogic 1 is no longer in active development
