### ISSUE TITLE
Proposal: Option to make speaking character come to front

### ISSUE THREAD

**Issue by Jowan-Spooner** [dialogic-godot/dialogic#1284]
from @EmmanuelHuazo #884:

In my game, I tend to have scenes with 3 or more characters, so sometimes they get behind other characters and it's tedious to add an "update node" just to get that character upfront before he talks.

![image](https://user-images.githubusercontent.com/79464276/166158696-706ea1f2-80b3-4676-86bc-6ea71883f068.png)

When "Dom" is talking he is still at the back...

![image](https://user-images.githubusercontent.com/79464276/166158808-18d5edeb-57bb-4d8f-bc49-cf4f85b04bf3.png)

**Comment by thebardsrc** [comment]
realistically, this doesn't even need any new code for implementation in Dialogic itself, it's already doable. have the portrait position listen to the 'Text.speaking_character' signal, and if the character speaking is the one in that position have it save the normal Z-index temporarily, bump the Z-index up so its in the front, then when that one isn't speaking anymore put it back to what it was set to before

also for portrait dimming, as well, which the screenshots reminded me of again. probly could update DialogicDefaultScene with both as options so theres an example of how to do it

**Comment by Jowan-Spooner** [comment]
Maybe make all the signals pass dictionaries instead? So it's easier to add more info to them?

**Comment by thebardsrc** [comment]
yup that was my thought as i was writing that up

**Comment by Jowan-Spooner** [comment]
This is now working with the simple_highlight_portrait.
