### ISSUE TITLE
Invalid index with Dictionary

### ISSUE THREAD

**Issue by an-joe-la15** [dialogic-godot/dialogic#1471]
## The problem
I am creating a quiz and have put the questions in the script (in an array). This seems to be disrupting dialogic from running alongside it.

I am not 100% sure and would appreciate some help with it.

![image](https://user-images.githubusercontent.com/79138013/225782744-023c649e-3c54-427d-858b-2d711dccc609.png)

that is the error message I get

this is my code for the questions:
![image](https://user-images.githubusercontent.com/79138013/225782847-cab0170e-ec58-4eeb-b1ff-4b02bb16150d.png)

Any idea to fix the issue or a link to the line of code that might be the cause for this problem

**Comment by CakeVR** [comment]
Is this still relevant? Maybe @zaknafean knows?
