### ISSUE TITLE
Timelines failing to start at all, something to do with not finding the character files.

### ISSUE THREAD

**Issue by SpacyCatgirl** [dialogic-godot/dialogic#1554]
## The problem

**Describe the bug**
Crash when trying to start timeline
"Invalid get index 'res://addons/Characters/character.dch' (on base: 'Dictionary')."

**To Reproduce**
1. Try to start a timeline in a scene.

**Expected behavior**
The timeline should start when pressing the button.

**Screenshots**
![image](https://github.com/coppolaemilio/dialogic/assets/118154787/fc2e4d2a-7359-4f5f-9ce2-128eba1a9e0b)
![image](https://github.com/coppolaemilio/dialogic/assets/118154787/4bc1b007-fdf7-4713-a4ca-fc3b4a11a45b)

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 4.2
 - Dialogic Version: Latest 4.2 early version

## Solutions

**Workaround**

No possible work around attemting to not  use a character just causes the timeline to not happen.

**Possible fixes**

Revert to whatever you were doing before.

**Comment by Jowan-Spooner** [comment]
I assume you meant 4.0.2. I haven't seen this before, will try to test it soon. 
On main there has been a fix for this sort of crash (removing non existing characters doesn't result in a cras anymore) although the root of the problem (why it thinks there is a character in addons/Characters) is very strange to me.

Are there any other things you have done (e.g. converted a 1.x project, loaded previous saves, manually edited the dialogic project settings, whatever...)?

**Comment by Kookiness** [comment]
This sounds like what is happening to me, but it might possibly be a result of me not being able to find adequate documentation to tell me if I'm doing things right.

**Comment by Jowan-Spooner** [comment]
Are you getting any error messages @Kookiness? If so could you screenshot them?

**Comment by Kookiness** [comment]
@Jowan-Spooner Yes, certainly! Thanks for the quick reply.

I'm not sure exactly what to enter for the first parameter for register_character() - I think I'm just doing it wrong.

![image_2023-08-31_18-20-03](https://github.com/coppolaemilio/dialogic/assets/75261412/9c9c49ff-700d-47d1-b853-23596976cd84)

It doesn't seem to want a string, but I'm not quite sure how else to direct it to the .dch file, if that's what I should be doing.

Any help appreciated!

**Comment by Jowan-Spooner** [comment]
Do a load(filepath) instead of just the file path.

**Comment by Kookiness** [comment]
Ahh, oops, of course. Thank you so much, that got it working!!

**Comment by Jowan-Spooner** [comment]
I don't think this is true anymore. If it happens again (with 4.2+ & Alpha 13+), feel free to reopen or create a new issue.
