### ISSUE TITLE
Edge case around variable type handling

### ISSUE THREAD

**Issue by vmedea** [dialogic-godot/dialogic#1599]
## The problem

**Describe the bug**

I have a variable that has string values. However, some of the possible strings that are assigned look like numbers eg `"0001"`. 

I try to use this variable in a choice condition that compares the variable against a string, but this gives an error "Expression failed to execute" due to type mismatch.

**To Reproduce**

See above.

**Expected behavior**

Exact typing: string variables are treated as strings, float variables as floats.

**System (please complete the following information):**
 - OS: Linux
 - Godot Version: 4.1dev
 - Dialogic Version: main [4a4f6b495a8a38257bfb07d422d9740fbc92b1a8]

## Solutions

**Workaround**

Don't use string values that look like floats. For example, prepend a letter.

**Possible fixes**

The direct reason for the error is that subsystem_expression, in the variable expansion code in `execute_string`, does

```gd
     value = str(dialogic.VAR.get_variable(...))
     if !value.is_valid_float():
```

So any variable value that looks like a float after being converted to a string, is treated like a float.

I tried to change this code to use `typeof(...) == TYPE_STRING` instead but it broke handling for floats instead, because it appears all variables are initialized to strings initially.  Probably this can only be fixed if variables in the variable tab get a type setting.

**Comment by Jowan-Spooner** [comment]
I will consider this closed. You can now give variables a specific type and the dialogic editor will try to keep you on the right path (keeping them on the same type) with those.

However there is no way of making sure a variable has the right type, so if anyone get's an error saying they are incorrectly comparing a integer to a string then they need to adjust their conditions.
