### ISSUE TITLE
Code: Trim trailing whitespace

### ISSUE THREAD

**Issue by and-rad** [dialogic-godot/dialogic#1624]
This isn't really a feature request nor a bug report. It's more of a request for convenience.

It would be great if you could remove all the trailing whitespace from the codebase and use some sort of editor setting to automatically do that in the future. As it is, the amount of trailing whitespace has become a minor inconvenience for us that constantly leads to diff noise and makes updating the addon somewhat of a hassle.

We're mostly using the addon on Godot 3.x projects, but I checked the 4.x version just to make sure, and there is still a good amount of this in the Dialogic 2 code.

**Comment by Jowan-Spooner** [comment]
We are now trying to avoid trailing whitespace for 2.x so I'll close this. As for the 1.x version, please open a separate request on the new [Dialogic 1.x repo](https://github.com/dialogic-godot/dialogic-1) if there is still interest.
