### ISSUE TITLE
TextBubbleLayout: Have option to list choices line-by-line

### ISSUE THREAD

**Issue by Kookiness** [dialogic-godot/dialogic#1734]
**Is your feature request related to a problem? Please describe.**
Yes. When using the "Text Bubble" style, choices are listed side by side, and often take up a lot of horizontal space, and leak far beyond the width of the speech bubble.

Screenshot included of what I'm currently experiencing when using the Text Bubble style with multiple choices, using the default font, font sizes, and speech bubble width:

![image](https://github.com/coppolaemilio/dialogic/assets/75261412/2f0edaf4-aff5-4403-a8df-e2bbb9128edc)

**Describe the solution you'd like**
Since sentences generally take up more horizontal space than vertical space, it makes sense to me to at least have an option to list choices vertically, like this:

Hello, Player 1! What do you want to talk about?
1. Choice 1: blablablablabla
2. Choice 2: testing 123 a really long line that could be about whatever
3. Choice 3: insert words here
4. Choice 4: who knows what this might say

It would also be nice to have this option available when using the other, non-Text-Bubble styles, too.

**Describe alternatives you've considered**
- Listing choices in the above way I described above could be the default or the only option, or
- Choices could be listed horizontally until they meet the predetermined bubble width, and then the next choice could wrap to the next line, or
- The bubble could be automatically expanded to fit all the choices (but this still wouldn't be ideal for wordy choices), or
- I could just decide to keep my choices really brief, which means I might need to compromise on how connected the player feels to the protagonist

**Additional context**
- I realise there's a way to set the max bubble width, but this doesn't solve the issue I'm having.
- I also realise Dialogic's currently still in alpha, so I'm hoping this feature request is helpful.
- Thanks for any consideration!

**Comment by hsandt** [comment]
Hey, I needed this option too but I don't see it anywhere in Settings > Choices.

In commit #2084 I do see a new variable "force_choices_on_separate_lines" but it's not exported and it's not used anywhere.

Was is supposed to be configured on TextBubble node or TextBubbleLayer node, and used to display choices on a VBoxContainer or via manual row placement?
