### ISSUE TITLE
Return concrete Type for Submodules

### ISSUE THREAD

**Issue by CakeVR** [dialogic-godot/dialogic#1816]
**Is your feature request related to a problem?**
The lack of proper submodule types introduces unsafe access.

For instance, when we use `Dialogic.Text`, we won't be able to work with the actual type nor does the compiler know whether the accessed properties exist.

An example, `:=` is not accepted:
```
var info := Dialogic.Text.get_autoadvance_info()
```

If we call `Dialogic.Text.random_fantasy_method()`, we won't get any warning either.

**Describe the solution you'd like**
We may need concrete class types for the submodules and a way to access them from `Dialogic`.

**Comment by Pheubel** [comment]
I am not sure how possible this would be in GDScript today, I am not too familiar with the whole code base, but if I am correct, these submodules get added dynamically, which makes it hard for static type system to figure out what they are supposed to be and if they exist at all. For the built in submodules you could get away by declaring them ahead of time, but extensions would have the short end of the stick. 

Using C# as an example, one way to go about it would be with generics.
```cs
public T GetSubSystem<T>(string name) where T : Submodule
{
    T module = GetNode(name) as T;

    if (module is null)
        throw new Exception($"subsystem \"{name}\" not found, make sure the path and type is correct");
    return module;
}
```

But GDScript seems to lack generics at this point in time, so this approach is not possible until then.

If it at some point does get introduced, it could looks something like this (warning, syntax speculation ahead)
```gd
func get_subsystem_as<T>(_name:String) -> T:
    var module := get_node(_name) as T
    assert(module != null)
    return module
```

This would not really a silver bullet for the problem, but would be a possible path a developer can walk with type safety.

**Comment by CakeVR** [comment]
It's possible with internal core submodules, by adding class names to them and then providing properties or methods to access returning declared concrete types. Additionally, using the `setget` feature is a possibility.
Right now, every access on `Dialogic.SubModule` is an unsafe call, this is not really nice.

However, this won't work for custom submodules, hence the solution is limited.

As you have mentioned, GDScript has no generics.

**Comment by Pheubel** [comment]
What naming convention would be good to follow for the submodule class names, something like `DialogicSubmoduleXXX` (for example `DialogicSubmoduleText`) is the first thing to come to my mind.

**Comment by Jowan-Spooner** [comment]
Definitely Subsystem instead of submodule (as Subsystem is what we use for these scripts everywhere else). 

But other then that yeah, `DialogicSubsystemText` (alternatively `DialogicSubsystem_Text`) or `DialogicTextSubsystem` I would say.
