### ISSUE TITLE
Timeline: Allow pretty name to be given to a timeline resource.

### ISSUE THREAD

**Issue by Pheubel** [dialogic-godot/dialogic#1918]
**Is your feature request related to a problem? Please describe.**
For my game i want to save the current progress, for the save slot i want to have a label with the name of the current timeline. However, as the files don't have a pretty name, the slot wouldn't have a pretty name.

**Describe the solution you'd like**
The timeline resource could have a field `pretty_name`, in which a developer can put in the name for the timeline that is not restricted by being a legal path. When no pretty name is given, it could fall back on the resource name instead.

**Describe alternatives you've considered**
I have tried to instead make use of meta data and add a field in there for the pretty name, but these would not be saved.

**Additional context**
N/A

**Comment by Jowan-Spooner** [comment]
@Pheubel Saving is the enemy for any feature like this. We wanted to make timelines easy to edit in any text-editor. But that also means EVERYTHING about the timeline has to be encoded in a text-like format inside of it.
Currently this does not include any metadata, only the events as text.

Would this be kinda unnecessary if #1891 was implemented? You could simply have a label with a nice name at the beginning of your timeline and use that?

I'm not against this, but as implementing a way of saving metadata is somewhat more complicated, I won't work on it very soon.
