### ISSUE TITLE
Game crashes if end_timeline() is used on [n+]

### ISSUE THREAD

**Issue by MindFlayeR57** [dialogic-godot/dialogic#1977]
## The problem

**Describe the bug**
the game crashes after end_timeline() is used while waiting for input on a [n+] event

**To Reproduce**
1. Go ingame to a line of dialog that has [n+]
2. trigger end_timeline()
3. left click
4. game crashes

**Expected behavior**
the game continues to run normally

**System**
 - OS: Windows
 - Godot Version: 4.2.1
 - Dialogic Version: 2.0 alpha 12

**Comment by Jowan-Spooner** [comment]
Pretty sure this has been fixed by #2045
