### ISSUE TITLE
Set Variable Addition not working

### ISSUE THREAD

**Issue by UsernameSquared** [dialogic-godot/dialogic#1984]
**Describe the bug**
While trying to make a choice add a number to a variable using the 'Set Variable + to itself plus str true' 
it does not work. I changed the value from string to bool to float to expression, yet none of them work, instead causing my timeline to crash when reaching beyond that point.

**To Reproduce**
Create a choice, add a set variable node within the choice, change '= to be' to '+ to itself plus', choose string, and 1 or true 
Same error for float or bool

**Expected behavior**
I expected the base variable to be expanded by one integer.

**System (please complete the following information):**
 - OS: MacOS
 - Godot Version: 4.2
 - Dialogic Version: 2.0 Alpha

## Solutions

**Workaround**

I have tried changing the float to string bool variable and expression, but it still didn't work

**Possible fixes**

According to the code its a problem in is subsystem_expression.gd:38 @executablestring(): Invalid operands to operator ==, float, and String

**Comment by Jowan-Spooner** [comment]
Could you be more specific in what dialogic version you are using? There are about 13 different dialogic 2 alpha versions.

**Comment by UsernameSquared** [comment]
Thank you for responding! Its Dialogic 2.0 Alpha-13

**Comment by Jowan-Spooner** [comment]
Hmm, I cannot recreate this. Here is my test setup:
![grafik](https://github.com/dialogic-godot/dialogic/assets/42868150/3ddf6e95-ce8a-4a51-a9b7-b3cc331f4d67)
```
Emilio: This is a cool timeline. {counter}, {Player.intelligence}
- yepe
	set {Player.intelligence} += "true"
	set {counter} += "hello"
- nope
	set {Player.intelligence} += "2"
	set {counter} += 4
jump
```

-> {counter} is setup either as INT or FLOAT and defaults to 10
-> {Player.intelligence} is setup as STRING, but defaults to "10"

The first choice doesn't change the value but also doesn't crash my game
The second one correctly changes both values.

Am I misunderstanding something?

**Comment by UsernameSquared** [comment]
Try adding an "if" command that only applies when the variable meets a certain point? I am not quite sure how my bug works, but it could be a problem with how the IF statement works after the variable change? Im sorry for my confusion and miscommunication but I am not an expert in this.

**Comment by UsernameSquared** [comment]
I
