### ISSUE TITLE
Character translations bug

### ISSUE THREAD

**Issue by WladekProd** [dialogic-godot/dialogic#1987]
## Translations bug

**Describe the bug**
When using translations, if there are more than 1 character when clicking on "Update CSV files", only one character will appear in the CSV file for translation. I found that in my character file, the "_translation_id" parameter is empty. When I try to fill it in and apply the translation, a zeroing of this parameter occurs. Unable to translate more than 1 character.

**To Reproduce**
1. Go to 'Character' and create 2 characters.
2. Go to 'Settings' -> 'Translations' and enable 'Enable Translations'.
3. Customize the translations folder and click 'Update CSV files'.
4. Open the file 'dialogic_character_translations.csv' in any text editor.

**Expected behavior**
I expected all my created characters to appear in the file so I could translate their names.

**Screenshots**
![234534](https://github.com/dialogic-godot/dialogic/assets/71282508/cfc5fec5-2736-4a14-b084-0a6828c9cad3)

**System (please complete the following information):**
 - OS: Windows 10
 - Godot Version: v4.1.3 stable
 - Dialogic Version: 2.0-Alpha-13
 
## Solutions

**Workaround**
I tried changing the '_translation_id' parameter manually, deleting and re-collecting translations, and recreating the character, but none of this worked.

**Comment by CakeVR** [comment]
Hello, thanks for opening this issue.

A character will be translated, if they appear in a timeline.
Please try including the character in a timeline and see if this resolves the problem.

**Comment by WladekProd** [comment]
> Hello, thanks for opening this issue.
> 
> A character will be translated, if they appear in a timeline. Please try including the character in a timeline and see if this resolves the problem.

In Timeline I have a dialog of 2 characters, but in the translation file only 1 character appears who starts the dialog first. The second character is not added to the file.
![12](https://github.com/dialogic-godot/dialogic/assets/71282508/eb450af9-c366-4a90-bc81-ac72ef63c291)

**Comment by CakeVR** [comment]
Thanks, I will look into this matter.

**Comment by CakeVR** [comment]
Hello, I fixed the bug! Thanks for your report.

However, due to the large amount of changes I have done to the translation system, you will find the fix to be part of this pull request: https://github.com/dialogic-godot/dialogic/pull/1954

This branch contains the new glossary translation and the character name fix.
