### ISSUE TITLE
Issue reparenting a nested Choice event

### ISSUE THREAD

**Issue by coppolaemilio** [dialogic-godot/dialogic#1993]
## The problem
Some times, when you create a choice event, you can't drag and drop it inside another already existing branch. 
It is a bit to explain but I show here in this gif how it works (errors not related, they are about image imports)

![weirdbug](https://github.com/dialogic-godot/dialogic/assets/2206700/1e9295ed-71e7-4714-89f8-844301ed5593)

**To Reproduce**

Create this timeline
```
Main text event
- button 1
	button 1 was pressed
- button 2
	you pressed button 2
- another one
```

Try to move the event "another one" inside the "button 2" one. 
If you can, toggle text and visual mode and try again. 

**System (please complete the following information):**
 - OS: Windows and Mac (tried and it happens in both machines)
 - Godot Version: 4.2.1
 - Dialogic Version: Alpha 13

## Solutions

When I saw this issue I edited from the text mode editor, but when the writer in my project found it didn't know why it was happening and didn't know how to fix it.

**Comment by Jowan-Spooner** [comment]
Btw, I will try to fix this but you can tell your writer that a choice can ALWAYS be moved if you select both the Choice event AND the End branch. 

But technically empty choices should also be moveable when just selecting the choice.

**Comment by Jowan-Spooner** [comment]
This should be resolved now.
