### ISSUE TITLE
Detached Dialogic 2 Window clears Timeline

### ISSUE THREAD

**Issue by CakeVR** [dialogic-godot/dialogic#1996]
## The problem

**Describe the bug**
Timeline empties when detaching the window.
**Saving will override the timeline with no content or whatever has been added while detaching!**

**To Reproduce**
I used the released Dialogic 2 Alpha 12.

1. Without detached Dialogic 2 window, open a timeline.
2. Detach the window.
3. Check if the timeline name is still there, contents must be empty now.

This state can be fixed by switching to any other Dialogic 2 tab and back.

**Expected behavior**
The content of the timeline is shown when detaching the window.

## Solutions

**Workaround**

As mentioned, switching tabs will fix this.

**Comment by Jowan-Spooner** [comment]
Do you think this could be saved by triggering a save before toggeling detachment? sounds like the easiest solution to me.
