### ISSUE TITLE
Error if the first Text Event has no speaker

### ISSUE THREAD

**Issue by CakeVR** [dialogic-godot/dialogic#1998]
## The problem

**Describe the bug**
If the first Text Event has no speaker, the following error emerges:
`Invalid type in GDScript utility function "load()". Cannot convert argument 1 from Nil to String.`

Happened in `subsystem_text.gd` line `329` using Dialogic 2 Alpha 12.

**Comment by Jowan-Spooner** [comment]
This can only happen if you call that method manually. But we should add a default to that get.

**Comment by CakeVR** [comment]
> This can only happen if you call that method manually. But we should add a default to that get.

Oh, indeed, I did that for my typewriter.
