### ISSUE TITLE
Auto advance doesn't stop after user input

### ISSUE THREAD

**Issue by MindFlayeR57** [dialogic-godot/dialogic#2022]
## The problem

**Describe the bug**
Dialogic.Input.auto_advance.enabled_until_user_input doesn't disable after user input

**To Reproduce**
1. Set Dialogic.Input.auto_advance.enabled_until_user_input to true
2. Press any button
3. Nothing happens.

**Expected behavior**
Auto advance stops

**System:**
 - OS: Windows 11
 - Godot Version: 4.2.1
 - Dialogic Version: 2.0 Alpha 12

**Comment by CakeVR** [comment]
Thanks for reporting, I will fix this.

**Comment by CakeVR** [comment]
Hello, I have fixed this bug, feel free to try out https://github.com/dialogic-godot/dialogic/pull/2024!

**Comment by MindFlayeR57** [comment]
Yep, that fixed it.

**Comment by CakeVR** [comment]
> Yep, that fixed it.

Great, thanks for confirming it!
