### ISSUE TITLE
Add Groups for Timelines & Characters

### ISSUE THREAD

**Issue by AutumnRivers** [dialogic-godot/dialogic#2033]
**Is your feature request related to a problem? Please describe.**
I'm currently working on a visual novel remake in Godot, using Dialogic. The main issue here is that the visual novel I am remaking is *massive*. Multiple books, multiple chapters, a whole slew of characters. The current issue I have right now is that the editor shows all these characters and timelines together, with no option to organize them.

**Describe the solution you'd like**
The ability to group together timelines and characters together in the main editor. This doesn't really have to change anything with how files are handled - this can be nothing more than a cosmetic change. Similar to how variables can be grouped.

There would be a separate icon next to "Create Timeline" and "Create Character" that would allow the developer to create a group. They could rename this group to whatever, and put either timelines or characters in it. Both, if they so wished.

**Describe alternatives you've considered**
Right now, I organize everything I need by starting each timeline/character's name with the category they're in. ex. Book 1 Chapter 1's timeline would be named `Book1_Ch1`, and Character A would be named `char_CharacterA`. This still leads to a fairly messy look, but it's better than nothing.

**Additional context**
I'm currently using Dialogic 2. As I stated above, this can be just a purely cosmetic change, and still require the usual unique identifies across all groups.

**Comment by CakeVR** [comment]
Thanks for your issue.

Just a small note, variable groups are implemented using `Dictionary`s and are more than just cosmetics.

**Comment by Jowan-Spooner** [comment]
My mistake, I used the wrong number. 
_There is only two proplems in computer science: Off by one errors._
Or something like that.

**Comment by Jowan-Spooner** [comment]
The sidebar has gotten some really nice updates and can now be set to auto-group the characters and timelines by the folder they are in. I feel like this should already improve the issues described here a lot.
