### ISSUE TITLE
Translations for character names are broken

### ISSUE THREAD

**Issue by MindFlayeR57** [dialogic-godot/dialogic#2037]
## The problem

**Describe the bug**
only some of the characters are automatically added to the dialogic_character_translations.csv file

**To Reproduce**
1. Go to the translation page in the settings
2. Click on Update CSV files
3. only some of the characters are added to the csv file

**Expected behavior**
all characters should be added to the csv file

**System (please complete the following information):**
 - OS: Windows 11
 - Godot Version: 4.2.1
 - Dialogic Version: 2.0 alpha 12

**Comment by Jowan-Spooner** [comment]
This sounds very similar to #1987 which might be fixed by a WIP PR already.

**Comment by MindFlayeR57** [comment]
Oh, it is the same bug, sorry for the duplicate.
