### ISSUE TITLE
 I hope to have the ability to separate the character avatar functionality within the conversation plugin, allowing for a customized effect.

### ISSUE THREAD

**Issue by NPSnuli** [dialogic-godot/dialogic#2053]
**Is there a method similar to using GDScript to create character avatars? I've noticed that currently, the character can only be represented as an image. My character is a 2D composite with various parts. Is it possible to make the character avatar more flexible by splitting it into different parts?**

**Comment by Jowan-Spooner** [comment]
Yes this is possible already by creating a custom portrait scene.

Here is the documentation for it: https://dialogic-docs.coppolaemilio.com/custom-portraits.html

Also this is not really a bug nor a feature request. For questions the discussions or even better emilio discord server are the better place!
