### ISSUE TITLE
Setting a variable to 0 causes it to be treated as null

### ISSUE THREAD

**Issue by tryinganon** [dialogic-godot/dialogic#2063]
## The problem

**Describe the bug**
If you have a bool or float (possibly others as well but I've only tested these two) that is set to be between 0 and another number, and place setting it within a condition based on the value of another float, you will get the error: "Dialogic: Set Variable event failed because one value wasn't set!"

**To Reproduce**
1. Make two variables in a new file, one float and one of either a float or a bool (may work with others too, these are just the two I had the problem with)
2. In a timeline, set (one of) the float(s) to a number (I personally used a random, but this requires fixing line 59 in event_variable to be "1,3,4,5: the_value = dialogic.VAR.get_variable(str(value))" for random number generation to work. I did check later to ensure that wasn't the problem, though, it does work with setting a user-chosen value from a fresh install of the plugin.)
3. Create a condition based on that first variable (such as >50), and within the if, set the second variable to 1. Within an else, set it to 0
4. Run the timeline
5: "Dialogic: Set Variable event failed because one value wasn't set!"

**Screenshots**

![image](https://github.com/dialogic-godot/dialogic/assets/158544849/7bd69359-81a0-4b21-8e76-7a494ae42741)

**Expected behavior**

The second variable should be set to 1 (or another number) or 0 based on the conditional statement (including bools being set to true or false).

**System (please complete the following information):**
 - OS: Windows 10
 - Godot Version: [4.2.1]
 - Dialogic Version: [2.0 Alpha 13]

## Solutions

**Workaround**

Setting it to 2 or 1 rather than 1 or 0 fixed it, and, interestingly, upon setting it back to 1 or 0, the error no longer happened, even with new variables. A fresh project, or setting it to a bool in the variable's tab (and even if that's then set back to a float), causes it to happen again.

**Possible fixes**

Line 54: if value and orig != null: in event_variable.gd is returning false. Using breakpoints, I have determined that "value" is the issue. It appears to be failing to get "value" earlier in the code, thus causing it to be null. Unfortunately, despite my best efforts, I can't seem to figure out why that is. I suspect it has to do with storing the variable's default from the variable's tab, though, because I noticed that when reloading the project, "set float to be zero" in the timeline changed to "set any to be (blank)". while "set float to be 1" was fine.

Whatever this is seems likely related to the addition of bools as a variable option, so, whatever aspects of code you guys changed for that is a good start I think?

(Also, I did get it to happen once or twice without the "conditional statement" aspect to this, but it was REALLY inconsistent and after flipping between a bool and a float a few times I couldn't get it to happen again with the same file anymore without the conditional part?? So idk, I wanted to give the most consistent method to trigger it)

(Let me know if I can provide more info or otherwise help)

**Comment by Atlinx** [comment]
What is the generated timeline script? Can you post the text that appears in the text editor (You can click the text editor button on the top right of the timeline to access the text editor)?

**Comment by tryinganon** [comment]
It's just "set {Test} =" which explains a lot lol
Manually changing it to "set {Test} = 0" does seem to fix it, so, maybe a visual editor issue?

**Comment by Atlinx** [comment]
> It's just "set {Test} =" which explains a lot lol
> Manually changing it to "set {Test} = 0" does seem to fix it, so, maybe a visual editor issue?

I see, that might be fixed by the PR I linked to this issue. Feel free to try my PR version out and lemme know if you were able to reproduce the error on there.
