### ISSUE TITLE
Set var node not updating timeline when set value type is changed. 

### ISSUE THREAD

**Issue by Atlinx** [dialogic-godot/dialogic#2067]
## The problem

**Describe the bug**

**To Reproduce**
1. Create variable `test_var` of any type
2. Create new timeline
3. Add `Set variable` node to timeline
4. Set `test_var` = `number` 0
5. Save
6. Switch to text editor and see that the timeline is correct
7. Change the set var type to a `bool`
8. Save
9. Switch to text editor and see that the timeline is still using the `number` and not the `bool`

**Expected behavior**
The timeline should be dirtied if the set var type is changed.

**Screenshots**
![var_value_type_update](https://github.com/dialogic-godot/dialogic/assets/25368491/c7dd5959-5450-4639-828d-0192e404f26c)

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 4.2.1.stable.official
 - Dialogic Version: 2.x (main)

## Solutions

**Workaround**
Changing the set var type and then changing the value will force a refresh.

**Possible fixes**
Unsure atm.

**Comment by Atlinx** [comment]
I'm working on a fix for this atm, and it seems like I'd have to update the value inside of the property setter of _value_type. However I'd need to get the default value of _value_type, and I'm not sure if there's a better way of doing things other than hardcoding the default values.

**Comment by SavinDevelop** [comment]
I have this problem that still exists in the latest version
