### ISSUE TITLE
Custom Portrait with a 3D scene 

### ISSUE THREAD

**Issue by AlexNight1986** [dialogic-godot/dialogic#2080]
## The problem

**Describe the bug**
When I try to use a custom portrait (a 3D animation scene inside sub-viewports)
An image of the scene appears above the editor and also a ghost/duplicate of the 3D model appears in the 3d viewport 

**To Reproduce**
1. Add a character
2. Add custom portrait
3. Select a scene with a 2DNode with SubViewportContainer>SubViewport>3D scene(containing the model/character, camera, etc)
5. enable "Top Level" on "SubViewportContainer" propeties
6. Go to Dialogic Tab and the error seems to appear when the scene is selected

**Expected behavior**
This "ghosts" or "duplicates" above the editor makes it difficult to navigate the editor
being unable to click or select the other functions 
**Screenshots**

![dialogic_bug](https://github.com/dialogic-godot/dialogic/assets/36001715/ea859ecf-23b1-46b4-a5e8-5b68628e5080)

**System (please complete the following information):**
 - OS: Windows 10
 - Godot Version: 4.2
 - Dialogic Version: 2.x

## Solutions

**Workaround**

N/A

**Possible fixes**

Resets the value to zero when selecting the scene in portrait settings

**Comment by Jowan-Spooner** [comment]
Why did you enable top-level on the SubViewport container? That explains why this happens and we should make sure not to allow stuff like this when showing the preview, but it would be useful to know why you wanted it. Top level would mess up the positioning in-game too.

**Comment by AlexNight1986** [comment]
Enabling Top Level was the only way of showing the portrait in-game, beacuse it seems Dialogic cant find the right position of the root node.
Thanks for the reply!

**Comment by Jowan-Spooner** [comment]
@AlexNight1986 Did you correctly overwrite the get_covered_rect method of the custom portrait? This the most likely cause for the portrait not showing up.

**Comment by AlexNight1986** [comment]
Honestly I haven't tried it.
"get_covered_rect" method is called in "_process"? or in " _ready"?

**Comment by Jowan-Spooner** [comment]
The method is called by dialogic to know the area of your portrait because Dialogic needs it to fit your portrait in the PortraitContainer.

I'm on my phone rn but it should look something like this:
```
func _get_covered_rect() -> Rect2:
     return Rect(Vector2(-half_width,-height), Vector2(width, height))
```
This assumes you've positioned the SubViewportContainer so that the root node of the portrait is at the bottom center of it.

If this doesn't work I can try to be more helpful later when I'm back at my PC.

**Comment by AlexNight1986** [comment]
I can make the portraits display without using the viewports, 3D scenes as children of a Node2d.
But when implementing backgrounds, they are always drawn in front. That's also why Top Level worked.

_get_covered_rect() seems to work correctly, but there are no entry or exit animations for both portraits and backgrounds.

**Comment by Jowan-Spooner** [comment]
@AlexNight1986 I don't think this is a problem with dialogic, rather your attempt at implementing the 3D portrait. If you still would like some help/advice, come and join emilios discord where we do general dialogic help!
