### ISSUE TITLE
Bug in Text box if Text Style's Next Indicator/Enable Toggle set to false

### ISSUE THREAD

**Issue by sonnguyen9800** [dialogic-godot/dialogic#2099]
## The problem

**Describe the bug**
Crashing when using Text event if the previous event implementing Style in which Next Indicator/Enabled set to False

**To Reproduce**
1. Go to **Styles** panel
2. Duplicate a new Style from the "Default" Style. Name it "Default 2"
3. Go to Style panel, select "Default 2" style, go to "Setting" -> "Other" subpanel and edit "Next Indicator" to false (toggled off) 
4. Create two character, character A implement "Default style", the other (Character B) implements "Default 2" style
5. Create timeline with two Text Event, the first one is for Character B, the second one is for Character A. The content of the text can be random
6. Run the timeline. After textbox 1 finish, the textbox 2 cannot appear. Crash happens.

**Logs**

```
E 0:00:02:0847   DialogicDefaultLayout.gd:130 @ _apply_export_overrides(): Node not found: "%NextIndicator" (relative to "/root/DefaultDialogNode").

  <C++ Error>    Method/function failed. Returning: nullptr

  <C++ Source>   scene/main/node.cpp:1638 @ get_node()

  <Stack Trace>  DialogicDefaultLayout.gd:130 @ _apply_export_overrides()
                 DialogicUtil.gd:255 @ apply_scene_export_overrides()
                 subsystem_styles.gd:43 @ add_layout_style()
                 event_text.gd:97 @ _execute()
```

**Expected behavior**
- No crash
- Textbox 2 appear normally within the timeline.

**Screenshots**
![image](https://github.com/dialogic-godot/dialogic/assets/45099020/0905fe87-10c6-4fb4-acdb-823ff292046b)
![image](https://github.com/dialogic-godot/dialogic/assets/45099020/0e89fb9b-bd76-474c-92f7-5f793dfe48ec)
![image](https://github.com/dialogic-godot/dialogic/assets/45099020/276cc1a4-ab17-473d-a86f-01c72e3d2bac)

**System (please complete the following information):**
 - OS: Window 10
 - Godot Version: 4.2
 - Dialogic Version: 2.0-Alpha-11 (Godot 4.1+)

**Comment by Jowan-Spooner** [comment]
Could you try this again with alpha-13?

**Comment by sonnguyen9800** [comment]
> Could you try this again with alpha-13?

Will do. Thank for the reply.

**Comment by sonnguyen9800** [comment]
At the moment I no longer encounter this bug since upgrading to alpha-13. Although there is a new bug which I just found but that one is related to the subsystem So I guess that we can safely close this Issue.

Thanks for the help!
