### ISSUE TITLE
A change to the way false boolean variables are assigned

### ISSUE THREAD

**Issue by kykysuperfly23** [dialogic-godot/dialogic#2112]
**Is your feature request related to a problem? Please describe.**
I tried to set a Boolean variable to false through the dialogic add on in this way: 
![image](https://github.com/dialogic-godot/dialogic/assets/89097049/67636d6e-d668-42de-937a-da78b138a33d)
![image](https://github.com/dialogic-godot/dialogic/assets/89097049/da69dc48-910b-4eaf-9589-ebe9df44336b)

but received this error: 
![image](https://github.com/dialogic-godot/dialogic/assets/89097049/7428fad1-3587-4d6e-80da-bc889268bdc1)

in order to set the boolean variable to false i put this into the text editor:
![image](https://github.com/dialogic-godot/dialogic/assets/89097049/aa6298ff-e654-47d1-a193-e308436306f7)

which resulted in this in the visual editor:
![image](https://github.com/dialogic-godot/dialogic/assets/89097049/12337c37-3c1a-426e-a115-5f159a0afdd7)

**Describe the solution you'd like**
I would like a false boolean variable to be easier to set in both the visual and text editor, because the current way is not quite intuitive.   I think the checkbox and the on/off slider make sense visually, it might just be a processing error.

**Comment by Jowan-Spooner** [comment]
@kykysuperfly23 What version are you using? There is a chance this has already been fixed on main.
