### ISSUE TITLE
Incrementing values in an autoload dictionary does not work.

### ISSUE THREAD

**Issue by coffeestains** [dialogic-godot/dialogic#2129]
## Changing values of a dictionary using dialogic fails silently.

**Describe the bug**
I've reported this on the discord but thought I'd open an issue here as well. If you use a GDScript autoload that holds values in a dictionary instead of  variables, and try to increment it using dialogic, it fails to increment without a warning.

**To Reproduce**
### **Autoload:**
```
var follower: {
"friendship": 10
}
```
### **dialogic text editor:**
```
Follower: I feel like dropping out of the guild and trying adventuring was a <bad/horrible/terrible> <idea/plan>.
I know but I will help you as much as I can.
  set {Globals.follower['friendship']} += 5
  Follower: I'm so happy you believe in me!
Tough luck. I hope you find a way to make things right.
  set {Globals.follower['friendship']} -= 5
  Follower: Right, that's the plan.
```

**Expected behavior**
Friendship should increment to 15 or 5 depending on selection but it stays at 10.

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 4.2.1
 - Dialogic Version: 2.0 Alpha1

## Solutions

**Workaround**

Using call events for now as a workaround.

**Comment by CakeVR** [comment]
As mentioned on the Discord, I was able to reproduce this bug.
