### ISSUE TITLE
Errors persist when Dialogic is removed from project. 

### ISSUE THREAD

**Issue by danfriedz** [dialogic-godot/dialogic#2130]
Hi,

A few months ago I trailed a few dialogue plugins and ended up going with another option for my current project.
I removed all references to the plugin but am still getting printed to the console implying the plugin is still somewhat present in the project.

- All dialogic files have been removed from my addons folder.
- Dialogic is no longer present under Project -> Project Settings -> Plugins

Any advice?
Thanks!

![image](https://github.com/dialogic-godot/dialogic/assets/61813510/aa9ca4a6-ab78-43a8-9f98-f062838972c5)

**Comment by Jowan-Spooner** [comment]
Try deleting the .godot folder in your project to force reload all the classes. This is usually a caching issue.

**Comment by danfriedz** [comment]
Thanks, Solved.
I thought I did this already but apparently didn't.
