### ISSUE TITLE
`EditorInterface` in `DialogicUtil` fails compiled Builds

### ISSUE THREAD

**Issue by CakeVR** [dialogic-godot/dialogic#2131]
The `update_autoload_subsystem_access` method invokes this to reimport `EditorInterface.get_resource_filesystem`, in order to reimport files after the custom subsystems were injected. 

Using an early-return if outside of the editor does not work, the sole existence of the `EditorInterface` will cause many errors to appear in the binary console window after a build.

This issue exists on commit 75ac265490b62e0426c95fd58134dc36d67eadc3.

If someone wants to fix this locally, just remove the line in question: https://github.com/dialogic-godot/dialogic/blob/75ac265490b62e0426c95fd58134dc36d67eadc3/addons/dialogic/Core/DialogicUtil.gd#L78

**Comment by rberends** [comment]
Thanks :) This broke an export of mine- removing the line bypasses this issue.
