### ISSUE TITLE
Not Able to run export game due to dialogic

### ISSUE THREAD

**Issue by vikram3** [dialogic-godot/dialogic#2139]
## Window Build Not working in last release Dialogic 2.0

**Expected behavior**
![image](https://github.com/dialogic-godot/dialogic/assets/28431707/ae2e24cb-27cf-4aa4-9252-f28924a6d964)

**System (please complete the following information):**
 - OS: [ Windows]
 - Godot Version: [4.2.1]

**Comment by CakeVR** [comment]
You provided no description at all.

Please try the latest Dialogic commit on the `main` branch.

**Comment by Jowan-Spooner** [comment]
@vikram3 This issue will be closed soon unless you can provide further information.

**Comment by vikram3** [comment]
Last release not working. But the recent latest repo is working. sorry, i didn't add details. i downloaded addon from assets library and its working fine in editor but when i export and run the build. The export game Crashed at startup due to dialogic addon. when its not enable. game not crashing.
![image](https://github.com/dialogic-godot/dialogic/assets/28431707/5daa3bdc-6672-42cc-99fc-dda0bfa09597)
![image](https://github.com/dialogic-godot/dialogic/assets/28431707/88810535-1424-4378-8fed-45d45690bf02)

**Comment by CakeVR** [comment]
Yes, this is a bug in Dialogic 2 Alpha 13, it has been fixed already!
Dialogic 2 is not on the Asset Library, though.
