### ISSUE TITLE
Inline conditions in Text Events

### ISSUE THREAD

**Issue by bhiltune** [dialogic-godot/dialogic#2142]
Currently there's no way to write inline conditions, meaning that you can't write a single Text Event and have the text within it vary based on different conditions and variable states. You have to make a wholly separate Text Event with the changes you want and check against a variable before showing it.

So essentially, the following Text Event is currently not possible:
stalwart_guide: Wow! That was a close one... [if {Condition.AlmostDied} == true](We almost died!)

(In the above case, the intended result is to only show the "We almost died!" suffix if the condition is true.

While it's possible to work around this, it's a bit annoying, especially when writing longer Text Events. This sort of functionality would make the system a lot more flexible in regards to variable dialogue, especially when dealing with very minor changes to the final text based on niche conditions, for example. IMO this would also fit in very well with the current options such as randomizing text and using variable names/values as text.

I'm not immediately sure how this could be implemented, but Godot's String class has a handy function called [Replace](https://docs.godotengine.org/en/stable/classes/class_string.html#class-string-method-replace) that could potentially work pretty well for something like this? 

In any case, this isn't a critical issue, but it would be a significant workflow improvement.

**Comment by Jowan-Spooner** [comment]
Hey @bhiltune,
I've just added a conditional modifier tag, so this will be available in the next version:
```
This is a text event. [if {SomeVariable} The variable is true/The variable is false]. 
```
