### ISSUE TITLE
Error when setting boolean variable to false

### ISSUE THREAD

**Issue by szyhar** [dialogic-godot/dialogic#2148]
## Error when setting boolean variable to false

The issue is as simple as can be. I ran into it when writing my very first test dialog, so I deleted everything to check just this one issue:

![Screenshot 2024-03-21 18 34 16](https://github.com/dialogic-godot/dialogic/assets/164392223/0033022f-c49f-4e84-ab77-2f4bd0570eff)
![Screenshot 2024-03-21 18 34 29](https://github.com/dialogic-godot/dialogic/assets/164392223/badbe3fe-c45f-43a7-a849-75a6c49c9c6c)
![Screenshot 2024-03-21 18 35 53](https://github.com/dialogic-godot/dialogic/assets/164392223/dcdb0b90-02c8-4bf2-a899-3321bb718253)

Here's the error message when I run the game:
![Screenshot 2024-03-21 18 35 21](https://github.com/dialogic-godot/dialogic/assets/164392223/0966d1b1-aaf2-48e5-b61d-4f3f50b5d301)

After reloading the project, the same message appears on startup.

When the variable is initially false and then gets assigned true everything works just fine.

EDIT: tried replicating the problem in another timeline and now, the message reads instead:

![Screenshot 2024-03-21 18 53 34](https://github.com/dialogic-godot/dialogic/assets/164392223/524f2b6b-496c-448b-8a18-fa1657af461a)

Once again, there is no problem when assigning the value true.

 - OS: Linux on ChromeOS 122
 - Godot Version: 4.2.1
 - Dialogic Version: 2.0-Alpha-13

I restarted Godot and deleted and then added Dialogic again to the addons. Neither changed anything.

Also, the reason I found this is that I froze the entire game before starting the timeline by changing a boolean global variable and wanted to unfreeze it at the end of the timeline. I'm new to Godot, would that be possible to do without changing the variable inside of Dialogic? Or could it perhaps become a feature to add the same expression to the beginning and end of each timeline?

Thanks for the great work you do!

**Comment by CakeVR** [comment]
Hello, can you try the latest commit on the `main` branch?

If you need assistance getting that working, here is our docs chapter for this: https://docs.dialogic.pro/getting-started.html#-how-to-install-the-latest-wip-version-

**Comment by szyhar** [comment]
> Hello, can you try the latest commit on the `main` branch?
> 
> If you need assistance getting that working, here is our docs chapter for this: https://docs.dialogic.pro/getting-started.html#-how-to-install-the-latest-wip-version-

Works now! Did I download the wrong version? I'm new to this stuff.

**Comment by CakeVR** [comment]
> > Hello, can you try the latest commit on the `main` branch?
> > If you need assistance getting that working, here is our docs chapter for this: https://docs.dialogic.pro/getting-started.html#-how-to-install-the-latest-wip-version-
> 
> Works now! Did I download the wrong version? I'm new to this stuff.

You downloaded Alpha 13, the latest release, which is correct. However, the bug you encountered was already fixed on our development branch, the `main` branch. That's why I suggested trying out the `main` branch.

I'm glad it works now!
