### ISSUE TITLE
The Tutorial Screen Flashes When A TimeLine Starts

### ISSUE THREAD

**Issue by FakerDomain** [dialogic-godot/dialogic#2158]
## The problem

**Describe the bug**
Version:Dialogic2-alpha-13

If I make the program wait a second before I start a tiemline the tutorial screen always flashes first.

The tutorial screen, I mean this one:
![图片](https://github.com/dialogic-godot/dialogic/assets/13235429/55c8ef03-b79c-4614-a100-b93bbaa66eb3)

**To Reproduce**
1. Make two characters with different name
2. Make a timeline and for every character prepare some dialogues
3. Make two simple Mark2D nodes in the main game scene
4. Before start the timeline, create a timer to wait for 1 second.
5. Start the timeline and register characters to Mark2D nodes, respectively.
6. Then run the game

My code is like this:
![图片](https://github.com/dialogic-godot/dialogic/assets/13235429/db7088ea-ff2f-49cf-b986-8805fd1be2a0)

**Screenshots**
![图片](https://github.com/dialogic-godot/dialogic/assets/13235429/35e51c4b-58ae-4da4-a1fd-2487be5ebedc)

**System (please complete the following information):**
 - OS: MACOS 14.2.1
 - Godot Version: 4.2.1 stable
 - Dialogic Version: 2.0-alpha-13

**Comment by Jowan-Spooner** [comment]
@FakerDomain could you try this again with the current main branch? A bunch of changes to the textbubble layout have been made, so it would be useful to know whether this is still a problem or not. Thank you very much!

**Comment by FakerDomain** [comment]
> @FakerDomain could you try this again with the current main branch? A bunch of changes to the textbubble layout have been made, so it would be useful to know whether this is still a problem or not. Thank you very much!

Sorry for replying so late, I have tried the main branch, and it seems that problem shows no more. I really appreciate your help!!~
