### ISSUE TITLE
Custom folder path

### ISSUE THREAD

**Issue by einord** [dialogic-godot/dialogic#2160]
**Is your feature request related to a problem? Please describe.**
The documentation tells that the folder to install the add-on must be in `res://addons/dialogic`. But this may conflict with the rest of the folder structure, and when not using this particular path dialogic will not run properly.

**Describe the solution you'd like**
It should be possible to modify this path in the settings of dialogic.

**Comment by einord** [comment]
Sorry @CakeVR my bad. I didn't know this was the preferred way.

**Comment by Jowan-Spooner** [comment]
Just to clarify, the location and naming of the addons folder is a godot-related thing. While we could try to allow for the plugin to work at a different path, godot will only recognize the plugin as an addon if it is placed in that folder. So unless that changes, this is not a thing we can do.

I will close this, but feel free to reopen it, if the situation changes or I misunderstood.
