### ISSUE TITLE
Error when attempting to load the plugin on macOS

### ISSUE THREAD

**Issue by thatenbykiki** [dialogic-godot/dialogic#2161]
## When I try to load the Dialogic 2 plugin within my project, I get an error.

**Describe the bug**
Unable to load addon script from path: 'res://addons/dialogic-main/addons/dialogic/plugin.gd'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/dialogic-main/addons/dialogic/plugin.cfg' to prevent further errors.

**To Reproduce**
1. Click the checkbox for Dialogic
2. Error displays

**Expected behavior**
Expected plugin to load. Plugin did not load.

**System (please complete the following information):**
 - OS: macOS 11.7.10
 - Godot Version: 4.2.0
 - Dialogic Version: 2.0-Alpha-13

**Comment by CakeVR** [comment]
Please follow the installation guideline: https://docs.dialogic.pro/getting-started.html

**Comment by thatenbykiki** [comment]
My apologies. Installing the add-on correctly fixes this issue. Thank you.
