### ISSUE TITLE
Renaming a style’s custom layer sets it to the default

### ISSUE THREAD

**Issue by Purgatory63** [dialogic-godot/dialogic#2188]
## The problem
Renaming a newly created style’s custom layer causes the custom layer to replace the premade layer.

**Describe the bug**

If you make a custom layer (my examples are custom text box layers) and rename it immediately (presumably any time after creating, as long as you don’t make a new style before renaming the file), it will cause the scene in the renamed file to somehow become the default, replacing the premade style.

Deleting the now default style causes you to be unable to make any new styles, and reloading the project will result in **all** styles (even if they seemed fine before) to vanish. Dragging their file back into the style bar results in no layers, only the default layer base.

I’ve got some videos of it, apologies that it’s pretty slow.

**To Reproduce**
1. Create a style based off the premade one
2. Make a layer (ex: text box) custom
3. Edit the newly created folder name for the custom layer
4. Create a new style also based off the premade one
5. Whatever layer you replaced will also be in the new style

**Expected behavior**
Naming the folder should only change its name, and the default layer should remain as the premade one.

**Videos**
https://youtu.be/lBML-5BfzcM?si=xmPhot3ySk2zRzxh (This one has timestamps to skip past me being slow)

https://youtu.be/cIr5fVWRx2g?si=5-E0m7eTpNBGMr39

https://youtu.be/Nh4aAhknv2Q?si=bkcrbCUaUVa_PmzW (Continuing (mostly) directly from the second video)

**System (please complete the following information):**
 - OS: Windows 10
 - Godot Version: 4.2.1.stable.mono.official
 - Dialogic Version: 2.0-Alpha-13

## Solutions

**Workaround**
What you tried to get the feature working:
I did not test with this part much, but it seems like creating a new style, then going back to edit the previous layers name doesn’t cause this glitch to happen (seen in 2nd video)

**Comment by Jowan-Spooner** [comment]
I think this issue has been fixed on main by #2387. However this fix will only work in new projects/when creating custom layers in the future.
