### ISSUE TITLE
Unexpected behavior with some auto advance setting

### ISSUE THREAD

**Issue by zaknafean** [dialogic-godot/dialogic#2190]
## The problem

**Describe the bug**
The auto advance settings are a bit misleading and can cause confusion as certain settings don't work as you'd expect. The issue we found involved
**Base Delay: 0
Additional Delay: None
Enabled: True**

The expected result to me and others would be that the text would auto advance after the text finishes appearing with no additional delay. But what happens is no auto advance occurs at all. However if you add even .01 to the base delay or add some sort of additional delay, it works fine.

In general you probably DO want some delay in an auto advance, but in that case we shouldn't allow the combination of base delay 0, additional delay none to exist.

**To Reproduce**
1. Go to settings
2. Use these settings
![image](https://github.com/dialogic-godot/dialogic/assets/7741797/f4aacdb5-edd8-4754-803e-b08847f33279)
3. Attempt to play a timeline
4. The timeline will not auto advance

**Expected behavior**
That the timeline will autoadvance, though to fast to read for most people.

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 4.2.1
 - Dialogic Version: alpha 13

## Solutions

**Workaround**

Adding any amount to base delay, or an additional delay fixes it.

**Possible fixes**
Easiest fix is to not allow a base delay of 0.

**Comment by Jowan-Spooner** [comment]
Yeah I could also fix autoadvance of 0 not working, although I agree that it likely has very few use-cases.

**Comment by Jowan-Spooner** [comment]
Actually I think I would just allow it and fix the bug. Having the delay at 0 is usually stupid, but I'm sure there are situations where it might make sense, especially when used with the autoadvance effect, for example if it should look as if someone was interrupted.
