### ISSUE TITLE
Invalid call register_character

### ISSUE THREAD

**Issue by doubleSheep66** [dialogic-godot/dialogic#2193]
## The problem

**Describe the bug**
Invalid call. Nonexistent function 'register_character' in base 'CanvasLayer (default_layout_base.gd)'.

**To Reproduce**
var layout = Dialogic.start("res://core/dialogic/timelines/timeline_unit.dtl")
layout.register_character(character_unit,dialogic_marker)

**Expected behavior**
I just use the example bubble style.

**Screenshots**
![image](https://github.com/dialogic-godot/dialogic/assets/53589453/54efa0cd-1faf-4f62-affb-75523d2cb68e)

**System (please complete the following information):**
 - OS: [Windows,]
 - Godot Version: [4.2.1]
 - Dialogic Version: [2.0 Alpha 13]

## Solutions

**Workaround**

What you tried to get the feature working

**Possible fixes**

Any idea to fix the issue or a link to the line of code that might be the cause for this problem

**Comment by Jowan-Spooner** [comment]
Is the textbubble layout your default style? You can make it the default by clicking the little Start button in the style editor.

**Comment by doubleSheep66** [comment]
![image](https://github.com/dialogic-godot/dialogic/assets/53589453/2212531b-28cd-452c-8e72-7b0f16fd4453)
![image](https://github.com/dialogic-godot/dialogic/assets/53589453/7e16efe6-914c-431c-8b16-31b7789eaa93)
I don't understand why register_character define in text_bubble_base.gd,but jump in to default_layout_base.gd when calling

**Comment by CakeVR** [comment]
Hello, as Jowan said, please verify whether the Text Bubble Layout is your default style.

**Comment by doubleSheep66** [comment]
> Hello, as Jowan said, please verify whether the Text Bubble Layout is your default style.

Hello,when I setted the default style and clicked the play timeline button ,it always displays bubble style.

**Comment by doubleSheep66** [comment]
Perhaps this is just a foolish problem for beginners, in short, it is now running normally. Thank you very much for your efforts

**Comment by Jowan-Spooner** [comment]
Glad you were able to fix it. 

You can make a style default with the STAR button on top of the style list. The default style is indeed marked by being yellow. So stuff like this should be solveable by selecting the textbubble style and then clicking the STAR button.

**Comment by Jowan-Spooner** [comment]
Yes because how would it know that you want the textbubble style? It is using a fallback style, but it is the vn-style.
