### ISSUE TITLE
Attempting to use TextBubble but the node does not appear in the node list

### ISSUE THREAD

**Issue by thatenbykiki** [dialogic-godot/dialogic#2207]
I'm trying to utilise the TextBubble style that is offered. I have the code set up to register the character but I don't have a `DialogicNode_TextBubble` in my nodes list. I am using Dialogic 2.0 Alpha-13 on Godot 4.2.1.

**Comment by Jowan-Spooner** [comment]
@thatenbykiki We will need a bit more information: Have you setup the style correctly (screenshot), how does the code look that starts your timeline and tries to register the character?

**Comment by Jowan-Spooner** [comment]
I will close this for lack of information provided. If you still need help, consider asking on the discord.
