### ISSUE TITLE
Dynamic Variable Callbacks for Runtime Evaluation in Editor

### ISSUE THREAD

**Issue by angedelamort** [dialogic-godot/dialogic#2216]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to manually add or update numerous game variables directly within the editor for scenarios like checking if a specific mission is completed or if a hero meets certain attribute thresholds. This becomes cumbersome and error-prone, especially when multiple variables need to be updated frequently based on game state changes.

**Describe the solution you'd like**
I propose the integration of dynamic variable callbacks into the editor. This would allow developers to register a callback function that determines the value of a variable at runtime based on the game's current state or other conditions. 

**Describe alternatives you've considered**
One alternative I considered was using the existing set_variable method to manually update each variable as required. However, this method is suboptimal because it involves updating each variable individually each time there's a change in the game state, which is not only inefficient but also prone to errors.

**Additional context**
The code I added in "addons/dialogic/Modules/Variable/subsystem_variables.gd" allows for a callback to be registered that checks certain conditions and updates the variable value accordingly:

```
var dynamic_variable_callback: Callable

func set_variable(variable_path):
   # ...
    if dynamic_variable_callback and dynamic_variable_callback.is_valid():
        value = dynamic_variable_callback.call(variable_path)
        if value != null:
            return value
   #...
```
This implementation helps streamline variable management, although it currently lacks the ability to test effectively in the editor, 

This structure should effectively communicate your feature request and the rationale behind it, helping the development team understand the value of this proposed feature.

**Comment by Jowan-Spooner** [comment]
Hey @angedelamort, this is an interesting idea. 

For dynamic checks, I would usually just suggest calling autoload methods instead. E.g. if you had a Missions autoload like this:
```
extends Node

enum Status {NOT_STARTED, IN_PROGRESS, DONE}


func mission_status(mission_name: String) -> int:
    # determine status:
    return status
```

And then in dialogic you can simply go `{Missions.mission_status("my_mission")} == Missions.Status.DONE` or something like that.

I would actually just consider allowing variables to be expressions, so a variable could be a complex expression in itself, like a call to an autoload method.

**Comment by angedelamort** [comment]
That's an interesting Idea using autoload methods. I wasn't sure to understand the doc.

From the [documentation](https://docs.dialogic.pro/variables.html#4-using-variables-outside-dialogic), I'm not sure how this would be done. You just use the autoload and expose a function and Dialogic will check for the string and call the method after the "." directly?

I will see if that works well in my C# environment.

By the way, I coded my own dialogue system and I needed some UI and so I started to look around and found what you guys did. I was very impressed. Very similar to what I've done, but way more features and UI lol. Really impressive work. Thanks for sharing.

**Comment by Jowan-Spooner** [comment]
The docs could probably be better for sure (they always can 😭).

Whatever is in {curly brackets} will be handled by multiple systems. Dialogic will first assume it's a dialogic variable, but if not, it will be passed to the Expression subsystem, which will use Godot's Expression class, with the autoloads passed in as objects. This allows quite a lot of script functionality to be used automatically.
I'm not personally using C# so that is a bit untested, but I don't see a reason why it shouldn't work tbh. 

Glad you are enjoying Dialogic so far :)!

**Comment by angedelamort** [comment]
This works great! The return signature is even a Variant, so it will do the trick perfectly!

for C#, the annoying part is that I have to create a C# interface to simplify the use in my code.

For example, you want to use the `+=` notation instead of the `Connect` or having to call `dialogicHandler.Call("start", timelinePath);` doesn't make it elegant either. If you're interested of creating such an interface, I'll be happy to share some of my code. But that's mainly boiler plate.

**Comment by Jowan-Spooner** [comment]
Yeah we had a C# wrapper at some point, but because none of the core-maintainers used C# much, it kept being out of date, so for the alpha period it's not planned, maybe once we get into beta, whenever that might happen 🙈 

Thank you for the offer though, feel free to contribute, but if you want to do so, chat with us on emilios discord first!
