### ISSUE TITLE
Unable to properly invoke variables in Dialogic.

### ISSUE THREAD

**Issue by NoaIce** [dialogic-godot/dialogic#2224]
**Describe the bug**

After setting up variables as float and int in Dialogic, when attempting to increase or decrease values in the timeline, all options become "="

**To Reproduce**

1.Setting up the label to display variables.
2.Pre-set variables to 20.
3.In the timeline, set options and specify "set {Variables} += 5".
4.Press F6, Variables = 20.
5.Execute the timeline, press the option, and Variables = 5.

**System (please complete the following information):**
 - OS: [ Windows ]
 - Godot Version: [4.2.2]
 - Dialogic Version: [2.0 Alpha-13] ->[(Main)2.0 Alpha-13]

**Comment by CakeVR** [comment]
Hello, please try the latest commit on the main branch!

**Comment by NoaIce** [comment]
Sorry, I don't understand what you mean by "in the latest commit on the main branch."
I only set up three variables in Dialogic.
In the root directory, like
Under Miya_var, HaveLike and HavePT
Because these variables were originally set for the character Miya
But during testing, I found that executing the timeline would overwrite existing values.
Later attempts revealed that
"+="
"-="
"*="
"/="
All these functionalities only execute the effect of "="


This is my setup.
![001](https://github.com/dialogic-godot/dialogic/assets/169447171/62171a64-1d1b-45bc-ba1d-d42f87ee06b3)
![002](https://github.com/dialogic-godot/dialogic/assets/169447171/4cde7bc2-b57a-4903-a3d6-5583062256e2)

And this is the scene I used for testing.
At the beginning, the preset values are correct.

![003](https://github.com/dialogic-godot/dialogic/assets/169447171/c4eb4dee-d7f7-40ae-a703-407cf8954a78)





When Option 1 is used, havelike +1, but the value of havelike becomes 1 instead of 21.
![004](https://github.com/dialogic-godot/dialogic/assets/169447171/4ca63038-964d-4a46-b575-735747b7bf09)

When Option 2 is used, like +5, but like becomes 5 instead of 25.
![005](https://github.com/dialogic-godot/dialogic/assets/169447171/97d32c2e-caac-49bb-8d46-37bc78708c36)


Here is the appearance of the timeline text editor.
![image](https://github.com/dialogic-godot/dialogic/assets/169447171/16135500-a6d2-4e6d-b4ea-0ec69011beb0)

**Comment by CakeVR** [comment]
What I meant by my previous post, is to update your Dialogic 2 version to the one you can find on the `main` branch on this repository. I provided the link on how you can achieve this in that post.

**Comment by NoaIce** [comment]
Oh, I see. My apologies.
I downloaded Dialogic for the first time yesterday, 
and this version is what I downloaded. I put all the data into res://. Is this the correct approach?


As shown in the picture
![image](https://github.com/dialogic-godot/dialogic/assets/169447171/4529e56b-d8ed-49e4-a9cf-4e1599db9c55)
![image](https://github.com/dialogic-godot/dialogic/assets/169447171/a9bc5b57-9390-4263-bc32-fbbe905eaeb8)

**Comment by CakeVR** [comment]
No, now you have two Dialogics installed.

The link I sent you has a previous category that walks you through the entire process: https://docs.dialogic.pro/getting-started.html#1-installation--activation

**Comment by NoaIce** [comment]
Oh, sorry for the confusion.
The "Dialogic" folder under assets is where I put the Dialogic character data... Wait, could this be the reason?

I've been working on this project for the past couple of days to test some addons. Before Dialogic, I was testing the Dialogue Manager. To distinguish between file types, I used the name "Dialogic."

I'm really sorry about that.

**Comment by CakeVR** [comment]
You also have the `Tests` folder installed, if you followed the link, this should not have been added to the root or anywhere in the project.

**Comment by NoaIce** [comment]
I created a new Godot project, installed Dialogic, and restarted.
Then I reconfigured the variables and modified them in the options.
However, the result remains the same.
This is the only code I'm using to display variables and activate the Timeline.
![image](https://github.com/dialogic-godot/dialogic/assets/169447171/678c60fb-3a76-4744-9322-e720650c2034)

Below are other settings

![image](https://github.com/dialogic-godot/dialogic/assets/169447171/8abc0b57-6ef1-484c-9d32-aff7e91eac83)
![image](https://github.com/dialogic-godot/dialogic/assets/169447171/b0a0eddc-d455-4237-bf89-831a896990c5)
![image](https://github.com/dialogic-godot/dialogic/assets/169447171/184e3a3b-f536-459f-9b0c-739ff53474f5)
![image](https://github.com/dialogic-godot/dialogic/assets/169447171/3911ffe1-3ddf-4dab-bb56-f9fdfb7ae33a)
![image](https://github.com/dialogic-godot/dialogic/assets/169447171/7c0bbd48-e684-4c50-94e9-e495c9e7ef2d)

**Comment by CakeVR** [comment]
If you have installed Alpha 13, you may have not followed my instruction to *install the `main` branch on this repository*.
Please ensure you have installed that version. You can verify this by showing the version at the bottom-left of the Dialogic tab window.

**Comment by NoaIce** [comment]
You mean this one, right?
![image](https://github.com/dialogic-godot/dialogic/assets/169447171/fc10646f-8b62-4b28-9918-9d560096e56f)


But I downloaded it from here...... 
Sorry, let me look again.

![image](https://github.com/dialogic-godot/dialogic/assets/169447171/0d115d4f-8cf1-4d1b-917c-21b1643d5756)


By the way, just to clarify, what should be displayed in the version number if it's correctly installed?

**Comment by NoaIce** [comment]
Ah... it seems like the issue might be with the Main file. 
I couldn't find any other versions,
so this time I went ahead and downloaded the file for version 2.0 Alpha-13. After testing it,
everything seems to be working fine.

![image](https://github.com/dialogic-godot/dialogic/assets/169447171/7082c2dc-d236-4ec5-b6c4-debe8126305d)

Do I need to change the version number at the top? But it also displays 2.0 Alpha-13.

![image](https://github.com/dialogic-godot/dialogic/assets/169447171/677591a7-078f-46a9-9f80-cb3e533f55ce)

**Comment by Jowan-Spooner** [comment]
I will close this as the original issue seems to have been resolved with an update. 
Uninstalling plugins can be easy (just disabled them and delete their folder), but of course plugins might have had an effect on your project, so your code/scenes might need adjustment if you used the plugin. If you need help uninstalling dialogic feel free to ask on the discord or in the discussions while please providing some more specific information on the errors you are getting.
