### ISSUE TITLE
subsystem_input.gd detects dialogic_default_action with non-exact match, causing it to advance on modifier combo input like Alt+Enter

### ISSUE THREAD

**Issue by hsandt** [dialogic-godot/dialogic#2249]
## The problem

**Describe the bug**
I map Alt+Enter to toggle fullscreen in my game. However, subsystem_input.gd detects dialogic_default_action with non-exact match, so Alt+Enter will be recognized as Enter and advance dialogue while also toggling fullscreen.

In addition, `get_viewport().set_input_as_handled()` is not called in `func handle_input`, so generally speaking it's not blocking other things, but if we want to call `get_viewport().set_input_as_handled()` later for safety, it will also block related inputs like Alt+Enter.

**To Reproduce**
1. Create some test timeline with multiple text nodes
2. Map Alt+Enter to some action like "test_action" and "dialogic_default_action" to start some timeline (this is just to demonstrate advance dialogue, this is not the very input that is tested so any input map will do to start the timeline).

```gd
# Custom script
func _unhandled_input(event: InputEvent):
	if event.is_action_pressed(&"test_action):
		print("test_action pressed")
		get_viewport().set_input_as_handled()
	if event.is_action_pressed(&"dialogic_default_action"):
		Dialogic.start("timeline")
		get_viewport().set_input_as_handled()
```

3. Press Alt+Enter: see both "test_action pressed" in output and dialogue advancing

**Expected behavior**
Alt+Enter should apply our custom action, and not advancing dialogue.

Or, if our custom action has low priority (not sure how to do this since Control priority is a bit tricky, so could not test this case), dialogue should advance but not also apply custom action (print).

**System (please complete the following information):**
- OS: Linux Ubuntu 22.04
- Godot Version: v4.2.1.stable.official [b09f793f5]
- Dialogic Version: main commit https://github.com/dialogic-godot/dialogic/commit/a9c56aa674c30cf242b2b87e5749235bd2d2fe53 (2024-05-05)

## Solutions

**Workaround**

In subsystem_input.gd, I modified code to check exact match:

```gd
## Unhandled Input is used for all NON-Mouse based inputs.
func _unhandled_input(event:InputEvent) -> void:
	if Input.is_action_just_pressed(ProjectSettings.get_setting('dialogic/text/input_action', 'dialogic_default_action'), true): # note true argument for exact match
```

(there are two more calls for mouse inputs where we could do the same, although modifier+mouse is less common)

I also used `exact_match: true` for my Custom script everywhere.

Finally, I added get_viewport().set_input_as_handled() after every input consumption, esp. ~~at the end of `func handle_input`~~. This doesn't really matter when all inputs are distinguished and use `exact_match`, but seems cleaner.

EDIT: consuming input at the end of `func handle_input` will block mouse control in menus. Instead, call `get_viewport().set_input_as_handled()` at the end of `_unhandled_input(event:InputEvent)` only.

**Possible fixes**

- We could hardcore `exact_match: true`
- We could add a Dialogic option to force `exact_match` if we really want to be retrocompatible with projects that rely on non-exact match

**Comment by Jowan-Spooner** [comment]
Hey, thanks for the report. I think setting it to exact for button/key inputs make sense.
