### ISSUE TITLE
Autoload order keeps changing when using Dialogic with another plugin (Maaack's Menus Template)

### ISSUE THREAD

**Issue by hsandt** [dialogic-godot/dialogic#2257]
## The problem

**Describe the bug**
This is a crossed bug, so I cannot say who's responsible: Godot, Dialogic or the other plugin Maaack's Menus Template.

Every day I launch the project and observe Autoload order has been changing, with either Dialogic's own Dialogic going to the bottom, or Maaack's Menus Template 4 singletons (AppConfig, SceneLoader, ProjectMusicController, ProjectUISoundController) going to the bottom.

![image](https://github.com/dialogic-godot/dialogic/assets/1067772/4c217b41-dd92-4ccf-87cc-97371ca5bebc)

This may be a limitation of Godot who cannot decide which plugin to initialize first, but still I don't see why it would reorder autoloads already added.

Sometimes, Maaack's Menus Template 4 singletons are completely removed from the project after issues like compile errors, I notice this after closing project sometimes, whereas Dialogic is never removed, so maybe Dialogic is not the culprit after all.

When working with a team I must tell my collaborators not to commit those autoload order change, it can create unwanted conflicts.

**To Reproduce**
1. Make a project and install both Maaack's Menus Template and Dialogic addons
2. Make sure that both plugins are enabled
3. Do some stuff (the less precise step, cannot find exact trigger conditions; you can try to trigger parse errors for instance)
4. Check VCS
5. Close project
6. Check VCS
7. Open project
8. Check VCS
9. Revert your stuff (e.g. fix parse errors)
10. Check VCS

**Expected behavior**
Autoload order should be stable

**System (please complete the following information):**
- OS: Linux Ubuntu 22.04
- Godot Version: v4.2.1.stable.official [b09f793f5]
- Dialogic Version: main commit https://github.com/dialogic-godot/dialogic/commit/a9c56aa674c30cf242b2b87e5749235bd2d2fe53 (2024-05-05)

## Solutions

**Workaround**

I just revert the change after closing the project, and make sure to never commit them.

**Possible fixes**

Godot / Maaack's Menus Template could avoid removing autoload singletons when there are project issues.

**Comment by CakeVR** [comment]
This has been fixed on the `main` branch already.
The branch is currently experimental, you can try and use it or backport the fix to your current version.
