### ISSUE TITLE
Choice block automatically displays “condition” settings

### ISSUE THREAD

**Issue by brylie** [dialogic-godot/dialogic#2272]
## The problem

Adding a choice automatically displays conditional item “if … “

**To Reproduce**
1. Download and install the latest pre-release (Alpha 14)
2. Create a timeline
3. Add a choice block
4. Hit the plus to add a choice option
5. Notice that the block contains a partially functional “condition” block

**Expected behavior**
The condition should be hidden until the user clicks the disclosure triangle.

**Screenshots**

I’m creating this issue on my mobile phone, sorry 🙂

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 4.2.2
 - Dialogic Version: 2 alpha-14

## Solutions

**Workaround**
We were able to work with the choice, but it was confusing 🫤 

**Possible fixes**

Any idea to fix the issue or a link to the line of code that might be the cause for this problem

**Comment by Jowan-Spooner** [comment]
Hmm... this is not a bug, but an intentional design decision. Any event that has settings in it's body will be opened when first created, because people often just didn't notice that the events even had expandable bodies, and also it's annoying to always have to unfold the body, especially when adding events (the body will be hidden when opening the timeline later).

Maybe we should rather make the UI more clear that if nothing is entered there the condition will be considered true and thus have no effect?

**Comment by brylie** [comment]
Ah that makes sense. I was confused by the UX since we weren’t using conditional logic to display the choice in our initial prototype.

By the way, in what section of the documentation should there be a description of the features and use cases for each timeline block type?

**Comment by Jowan-Spooner** [comment]
Unfortunately we have not gotten around to making documentation for all the events yet.

**Comment by brylie** [comment]
I’d like to help with documentation. What is the recommended structure?

**Comment by CakeVR** [comment]
You can learn everything about the documentation here: https://github.com/dialogic-godot/documentation/

**Comment by brylie** [comment]
Thank you. FWIW, I was working with a friend to use Dialogic in a game project and we encountered some errors where we had somehow accidentally entered some text in the condition settings which caused the timeline to keep crashing. It was a fairly opaque error which had us stumped. We ended up removing the choice from the timeline and re-adding it to get things working again.

**Comment by Jowan-Spooner** [comment]
If you remember what you entered to cause the bug, feel free to create a bug report!

**Comment by brylie** [comment]
I think we had just accidentally clicked the input and maybe hit a random letter like `q`, so it wasn't a bug per-se but a confusing UX. Granted, we're learning Dialogic so understand that most of the responsibility is on us for making mistakes. I think the UX here could be a bit simpler by hiding the conditions at first and clearly showing the disclosure triangle for advanced users who need to set conditions on the choices 😄

**Comment by Jowan-Spooner** [comment]
I have improved the UX of the choice condition for the next version.
