### ISSUE TITLE
Change the color of choice button based on the choice

### ISSUE THREAD

**Issue by MohammadEbrahimi12** [dialogic-godot/dialogic#2286]
Hi,I'm making a multiple choice game which includes different kind of choices for example some choices can be asked twice some only once some are related to story and some are related to gameplay.i wanted to differentiate these choices by color for example the choices that you select twice blue and choice that you can choose only once red.i thoughtabout using signals but I can't access the choice button using code. Any idea how i do this with gdscript in dialogic.thank you.

**Comment by Jowan-Spooner** [comment]
Doing this is really hard right now, I'm not sure what the best way would be.
Something like this is planned though, we want to add a "custom_info" field to choices, which you can then interpret however you want when you show the choices. 
Can't promise this will make it to alpha 15, but there is a chance.

**Comment by MohammadEbrahimi12** [comment]
So you don't think there is any way to do it in the current version of dialogic?

**Comment by MohammadEbrahimi12** [comment]
So you don't think there is any way to do it in the current version of dialogic?

**Comment by Jowan-Spooner** [comment]
Hey @MohammadEbrahimi12,
sorry this was auto-closed. I have now added an extra-data feature to choices that can be used to achieve custom effects/stylings on choices. 
So this should be possible in the next version:
```
- This is a choice event | [extra_data="{"color":"red"}"]
- This is a choice event | [extra_data="{"color":"green"}"]
```

To apply this you will want to have a custom choice layer and your choice-button-nodes should have a custom script like this:
```gdscript
extends DialogicNode_ChoiceButton

func _load_info(info:Dictionary) -> void:
     super()
     if info.has("color"):
          match info.color:
                "red":
                      modulate = Color.RED
                "green":
                      modulate = Color.GREEN
```
