### ISSUE TITLE
Dialogue Disappears When Pressing Space Key at Runtime

### ISSUE THREAD

**Issue by SeveralCode** [dialogic-godot/dialogic#2297]
## The problem

**Describe the bug**
During gameplay, pressing the space key causes the dialog box to unexpectedly disappear. This issue occurs consistently, interrupting the flow of the game and preventing players from reading the dialog.

**To Reproduce**

1. Start the game.
2. Progress to a point where a dialog box appears.
3. Press the space key.
4. Observe that the dialog box disappears.

**Expected behavior**
Pressing the space key should either advance the dialog or have no effect, but it should not cause the dialog to disappear.

**System (please complete the following information):**
 - OS: Windows 11
 - Godot Version: 4.2.2
 - Dialogic Version: Apha-14

**Comment by Jowan-Spooner** [comment]
I cannot recreated this. Space correctly advances dialog for me without hiding it at all. Are you sure this isn't because some other thing in your game get's activated by space as well?

**Comment by SeveralCode** [comment]
What I have noticed is that when testing a dialogue with the space key, it progresses normally. However, when I perform the same action in an executable, the dialogue disappears.

However, I want to check my game modules to avoid wasting your time further in case it is an issue with my game code.

**Comment by Jowan-Spooner** [comment]
I will test an exported game, thanks for the clarification.

**Comment by SeveralCode** [comment]
Hi Jowan,

I have checked all the game modules and there doesn't seem to be anything that directly interferes with the dialogue system. The dialogues are executed using a handler that reacts to button presses.

I have attached some images to give you a clearer idea of what happens during the game's execution.

Dialogue Started: 
![image](https://github.com/dialogic-godot/dialogic/assets/58974039/0593c0da-f350-4648-bcbb-dbb45da97e3a)

Space Key Pressed:
![image](https://github.com/dialogic-godot/dialogic/assets/58974039/9cdf3c7d-fd38-4651-8a05-b137aafdbaf1)

Here you can find the implementation of my handler, although I believe it is quite straightforward.
``` 
extends VisualNovelActionHandler

## handle a specific action
func handle(time_cost : float, energy_cost : float): 
	Dialogic.start("res://timelines/actions/wheat_fields.dtl")
```
The only thing I haven't checked yet are the custom styles, although I have noticed that the same issue occurs even with the default style. Additionally, pressing the Enter key results in the same behavior.

**Comment by Jowan-Spooner** [comment]
I can't recreate it @SeveralCode . Would be really cool if you could make a minimal reproduction project where this happens!

**Comment by SeveralCode** [comment]
Hello @Jowan-Spooner, 

I believe I have resolved the issue. I neglected to mention that my game, being a point-and-click adventure, utilizes on-screen button clicks to trigger timelines using the '**Dialogic.Start**(...)' method. However, I overlooked that in Godot's built-in input map, both '_ui_select_' and '_ui_accept_' are mapped to the space and enter keys, which are used to interact with the UI and to progress dialogues. Consequently, pressing either of these keys inadvertently retriggered the Dialogic timeline start function, causing the error we discussed earlier.

To address this, I updated the game framework to include state management that differentiates when the player is actively engaged in a dialogue versus when they are not. This prevents the re-initialization of a timeline if it is already in progress.

Since this issue stemmed from a design flaw in my implementation rather than an internal problem with Dialogic, I will be closing this issue. Thank you for your time and assistance.

**Comment by Jowan-Spooner** [comment]
@SeveralCode Glad you found a fix. Good state management is the best solution here for sure, though in our FAQ we also mention a somewhat simple way to avoid this: https://docs.dialogic.pro/faq.html#my-input-action-to-start-dialog-conflicts-with-the-advancing-input-action
I wish you much success with your project, looks cool!
