### ISSUE TITLE
The timeline doesn't stop.

### ISSUE THREAD

**Issue by KirboTheDirbo** [dialogic-godot/dialogic#2302]
## The problem

**Describe the bug**
Basically when the timeline stops it starts again.

**Why I think this might be happening**
In my testing I figured out that if I use an impult lets call "talk" ti start the timeline and continue the timeline and then end the timeline using the talk input then the timeline restarts.

**Expected behavior**
When talk is pressed to end the timeline, pressing talk a second time will cause the timeline to start.

**Version info:**
 - Windows OS
 - Godot 4.2.2
 - Dialogic 2.0 alpha 14

## Solutions

**Workaround**

I used different keys to start and advance the timeline, but I don't find this very appealing.

**Possible fixes**

I don't really know. If you want to see the script then it is down here:

`func _process(delta):
	
	if player_in_area:
		if Input.is_action_just_pressed("talk"):
			run_dialogue(load("res://dialogue/test.dtl"))`
player_in_area just checks if the player is inside of an area2D.

**Comment by Jowan-Spooner** [comment]
Can you share the run_dialog() function? It's unclear whether you check at all if any dialog is already running before starting a new one.

**Comment by KirboTheDirbo** [comment]
K
Here is run dialogue
func run_dialogue(dialoguePath):
	print(dialoguePath)
	var layout = Dialogic.start(dialoguePath)
	layout.register_character(load("res://characters/npcs/hello.dch"), marker)
I'm using a textbubble style so thats why the third line is there.

**Comment by Jowan-Spooner** [comment]
Hey @KirboTheDirbo,
make sure that you are not starting another dialog if there is already a dialog running. 
You can find the code snippet here: [FAQ: My input action to start dialog conflicts with the advancing input action](https://docs.dialogic.pro/faq.html#my-input-action-to-start-dialog-conflicts-with-the-advancing-input-action)]
Let us know if that helps.

**Comment by KirboTheDirbo** [comment]
I fixed it but I don't know how. Maybe moving it out of the process function is what fixed it but I'm not too sure.
