### ISSUE TITLE
Null error for textbox animations

### ISSUE THREAD

**Issue by iron-beagle** [dialogic-godot/dialogic#2303]
## The problem

**Describe the bug**

Null error for `_on_textbox_new_text()` in `animations.gd`

**To Reproduce**
1. Create a custom style
2. Go to the visual novel layer
3. Add the default Wiggle animation for `New Text`
4. Play a timeline that will generate the New Text
5. See error

**Expected behavior**
The application not to crash

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 4.2.2 stable
 - Dialogic Version: 2.0 alpha 14

## Solutions

**Possible fixes**

on line 76 of `animations.gd` pluralize `&'Animation'` -> `&'Animations'` 

works for me now

**Comment by Jowan-Spooner** [comment]
That makes sense, good catch, thanks for the report!
