### ISSUE TITLE
Not able to play the timeline in-game more than once

### ISSUE THREAD

**Issue by Adi1614** [dialogic-godot/dialogic#2321]
## When I go back to my npc to re-watch the timeline, it gives an error "trying to return a previously freed instance".

I have chosen the visual novel style and I have a NPC that has a timeline associated with it, and once I interact with the NPC and try to comeback and have the same conversation (re-watch the timeline) the game crashes due to the above mentioned error. It is not an error in my scripts. It is an error in 557th line of subsystem_portraits.gd.

**To Reproduce**
1. Make a character and make a timeline with it. 
2. Make an area 2d to trigger the timeline and finish it.
3. Move a little further and come back to have to same conversation.

**Expected behavior**
Expected the timeline to begin again and run as it as ran the previous time.

**Screenshots**
![image](https://github.com/dialogic-godot/dialogic/assets/168962480/353bb023-c43b-4697-8a13-5478dfa9fdce)

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 4.2.2
 - Dialogic Version: 2.0

**Comment by Jowan-Spooner** [comment]
Can you share what version of dialogic 2 you use and the code you use to start that timeline?

**Comment by Owen-Tam** [comment]
![image](https://github.com/dialogic-godot/dialogic/assets/67542139/e9753889-3f5b-4fd4-b4c6-311dcc80efe0)
I'm facing the error with this code, on Dialogic 2.0

**Comment by Jowan-Spooner** [comment]
There are many (alpha) versions of Dialogic 2, it's quite important to know which one specifically you are on. The latest release for example is Dialogic 2 alpha 14. The version is indicated in the lower left of the dialogic interface or on the dialogic home screen.

**Comment by Adi1614** [comment]
> There are many (alpha) versions of Dialogic 2, it's quite important to know which one specifically you are on. The latest release for example is Dialogic 2 alpha 14. The version is indicated in the lower left of the dialogic interface or on the dialogic home screen.

i am using dialogic 2  Alpha 15

and one thing i noticed was that, i can play only one timeline. What i mean is that I have two timelines right now, one activates when my character moves too close to the water, and the other one is the NPC one. So if I talk to the NPC and then go near the water, i will face the same error mentioned in the main post and this is true for the other way around too, that is if i go near the water and then come to my NPC to talk, it will throw that error.


Here is my script:
![Screenshot 2024-07-01 212426](https://github.com/dialogic-godot/dialogic/assets/168962480/192c036a-8c33-41cd-9dfc-d25d69100491)

(script to start the dialogue)

![image](https://github.com/dialogic-godot/dialogic/assets/168962480/6772494f-3332-4a09-9528-c51e42288502)

(calling that function here)
This was for my NPC.

![image](https://github.com/dialogic-godot/dialogic/assets/168962480/dbcdff4e-aa89-45a6-b530-0a63d47028a0)

(This is the water detection timeline)

Don't mind the NearWater variable, I was thinking for a way to fix this issue, but that was not it.
Please look into it

**Comment by Adi1614** [comment]
@Jowan-Spooner any fixes yet?

**Comment by Jowan-Spooner** [comment]
Hey @Adi1614 I have not been able to reproduce this yet. If anyone could make a Minimal Reproduction Project and share it here or send it to me on discord, that could help a lot.

**Comment by Adi1614** [comment]
[test1.zip](https://github.com/user-attachments/files/16072851/test1.zip)

@Jowan-Spooner i have made this small project to imitate the error. i have tried starting the dialog from every node possible to see if it makes any difference, but it didn't. Currently the dialogue is being called in the Area2D script which is associated with the NPC. You will get to know once you open it up. Thank you

**Comment by Jowan-Spooner** [comment]
Thank you, I will try it right now.

**Comment by Jowan-Spooner** [comment]
@Adi1614 Sorry, this was autoclosed, but I'm hoping it's actually fixed on the main branch now. If you could try and let me know if it works for you now, that would be perfect!

**Comment by Adi1614** [comment]
@Jowan-Spooner I'm really sorry for the late response. I am quite new to github, if you can just tell mw how should i update the dialogic with the new changes you have done it would be really helpful. I am really sorry for being a little childish but im relatively new to github and all these things. I will report you is the issue is fixed on my end as soon as possible.

**Comment by Jowan-Spooner** [comment]
No worries, check out this explanation on our Getting Started page and the section below it "How to install the latest WIP changes": https://docs.dialogic.pro/getting-started.html#1-installation--activation
If you still have questions, feel free to ask here or on the discord.

**Comment by Adi1614** [comment]
@Jowan-Spooner Yes, the issue is fixed. Thank you very much for the support I really appreciate it😊.
