### ISSUE TITLE
Background Transition Blurry (Linear Filtering)

### ISSUE THREAD

**Issue by NatePlays95** [dialogic-godot/dialogic#2322]
## The problem

**Describe the bug**
Background image transitions become blurry during any of the default background transitions, despite the chosen default texture filtering in Project Settings

**To Reproduce**
- Set project setting ``rendering/textures/canvas_textures/default_texture_filter`` to Nearest.
- Get a pixelated / low resolution image to use, like a texture from Spriters Resource.
- Make a new Timeline.
- Set a Simple Fade or Push transition to a pixelated / low-res background image (Make it slow for easy notice).
- Preview Timeline.

**Expected behavior**
The filtering mode for the background transition shaders should respect the filtering mode I set as default in the editor in ``rendering/textures/canvas_textures/default_texture_filter``, and I possibly be able to edit the filtering mode as a setting of the BackgroundLayer in the style editor.

**Screenshots**

How it is supposed to look (paused during a transition):
![image](https://github.com/dialogic-godot/dialogic/assets/74799857/6acc49ec-9320-46e0-b0ec-40be4c4992bb)

How it looks by default:
![image](https://github.com/dialogic-godot/dialogic/assets/74799857/050679c5-bc87-42cb-b042-821d5abd191e)

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 4.2
 - Dialogic Version: 2 alpha 14

## Solutions

**Workaround**

My game is made entirely with pixel art so I can afford modifying the default shaders directly.
![image](https://github.com/dialogic-godot/dialogic/assets/74799857/6e4b9ac3-2666-40e9-b582-f0fd1d114cd6)

**Possible fixes**
If possible, these sampler filter types should be set to the system default when the shader is instantiated.

**Comment by Jowan-Spooner** [comment]
I agree that this would be better behaviour, though I'm not sure if this is possible without switching out the whole shader. 
This seems to be the relevant godot issue: https://github.com/godotengine/godot/issues/57679

**Comment by Jowan-Spooner** [comment]
Hey @NatePlays95 I've made a PR that might fix this issue: #2339 
If you could try the PR and tell me whether it fixes the problem for you, that would be useful!

**Comment by Jowan-Spooner** [comment]
Hey, so I've merged the PR as it seemed to fix the issue in my tests. Still would appreciate if you could let me know if it has been fixed for you as well.

**Comment by NatePlays95** [comment]
I missed the notifs, sorry!
I have replaced the dialogic files in that project for the files in main to test, and have been getting this error on test timeline and on the normal game, probably unrelated as the files affected are not from your PR.
![image](https://github.com/user-attachments/assets/cbea6af5-468b-417b-8ad8-6a4968a2d5ba)

I'm still new to open source contributing so i'll try to test just your PR.
