### ISSUE TITLE
"This is a fallback bubble..." Tooltip appearing for one frame before dialogue actually starts. 

### ISSUE THREAD

**Issue by PixelMariachi** [dialogic-godot/dialogic#2338]
Description of the bug:

I believe this video will explain it perfectly. It doesn't *always* happen but it's almost every time, no matter if you quickly interact with characters or wait a minute around before actually interacting, 95% of the times it happens.

https://github.com/dialogic-godot/dialogic/assets/104698416/a9fe1c88-e63a-40f1-9196-8663fe3070d7

To reproduce:

This is the code for my NPC's. I'm new to coding so hopefully the fix is simply something stupid I don't know how to do yet, but my attempts to fix it on my own have been futile so far so I ask here:

```
extends CharacterBody3D

var player_in_area = false
var monitoring = true
var has_met_loaf = false

func _ready():
	pass

func _process(delta):
		if player_in_area:
			if Input.is_action_just_pressed("e"):
				if has_met_loaf == false:
					run_dialogue("Loafchat")
					has_met_loaf = true
				elif has_met_loaf == true:
					run_dialogue("Loafchat2")
					
					


func run_dialogue(dialogue_string):
	var layout = Dialogic.start(dialogue_string)
	layout.register_character(load("res://Characters/NPCS/Loaf.dch"),$".")
	
	
	
func _on_chat_detection_body_entered(body):
	if body.has_method("player"):
		player_in_area = true


func _on_chat_detection_body_exited(body):
	if body.has_method("player"):
		player_in_area = false
```
**Expected behavior**
The tooltip shouldn't appear at all.

**Screenshots**
Here's an image of the tooltip for those who don't know which one I'm talking about:

![BugReport](https://github.com/dialogic-godot/dialogic/assets/104698416/25c253b0-e58e-4f8a-96cd-62c468d0b5d4)

**System (please complete the following information):**
 - OS: Windows 10
 - Godot Version: 4.2.2 stable
 - Dialogic Version: 2.0 Alpha 15
 - 
## Solutions

Go into the TextbubbleBase layer scene res://addons/dialogic/Modules/DefaultLayoutParts/Base_TextBubble/text_bubble_base.tscn and then hide the Example node, then save the scene.

Do this if it's not by default in the newer versions of Dialogic

**Workaround**
None found yet, it boils down to "be lucky enough it doesnt happen" atm. I have tried using the prepare method as the documentation says, as well as some workarounds to try preload the character or even the dialogue itself beforehand but my coding skills are heavily lacking. The code above is how I originally had it without any preloading.

**Possible fixes**

I have successfuly preloaded the character while testing but it seems to be more of an issue with the dialogue connecting to the character itself, since that didn't fix the issue. Perhaps getting the code to preload said connection would fix it, since the tooltip only appears for one frame befre actually connecting. I had a friend on a way higher end PC test it too and he had the same exact issue so at least I know it's not a me problem.

**Comment by Jowan-Spooner** [comment]
@PixelMariachi This has been reported before, but I've never been able to get it myself (by sheer luck it seems). 
The easiest way to fix this might be to hide the whole message by default. Could you try whether that fixes it for you:
- Go into the TextbubbleBase layer scene `res://addons/dialogic/Modules/DefaultLayoutParts/Base_TextBubble/text_bubble_base.tscn` and then hide the `Example` node, then save the scene.

If that fixes it for you then we can certainly make it the default.

**Comment by PixelMariachi** [comment]
> @PixelMariachi This has been reported before, but I've never been able to get it myself (by sheer luck it seems). The easiest way to fix this might be to hide the whole message by default. Could you try whether that fixes it for you:
> 
> * Go into the TextbubbleBase layer scene `res://addons/dialogic/Modules/DefaultLayoutParts/Base_TextBubble/text_bubble_base.tscn` and then hide the `Example` node, then save the scene.
> 
> If that fixes it for you then we can certainly make it the default.

That fixed it!! Thank you very much. I find the tooltip is useful so perhaps adding this way of disabling it as "If this text flashes before connecting to a dialogue, disable it here:" would be the best way to go about it. I tried timers and everything and it still wouldn't work so yeah this is it.

**Comment by Jowan-Spooner** [comment]
But the tooltip will be re-shown if the layout is used incorrectly anyways (if a non-registered character speaks). It should just not be visible at the start by default.

Thanks for testing, I will make sure to make PR later.

**Comment by PixelMariachi** [comment]
If you want I can always send you the little build I did since that happened in there too to my friend, or even the project itself (I just started so it's very small) but I wouldn't know how to send it

**Comment by PixelMariachi** [comment]
Nevermind I remembered I have it uploaded to drive, here it is if you want it:

https://drive.google.com/drive/folders/1ykkQk5R3P3wRH44uDVfJBFt6KF1aD6pO

**Comment by PixelMariachi** [comment]
Alrighty I'll delete the link then! No probs :>
