### ISSUE TITLE
Out of bounds get index '-1' (on base: 'Array')

### ISSUE THREAD

**Issue by kevzettler** [dialogic-godot/dialogic#2353]
## The problem

**Describe the bug**
Dialogic crashes on the `is_voiced` function

```
## Whether the current event is a text event and has a voice
## event before it.
func is_voiced(index: int) -> bool:
	if dialogic.current_timeline_events[index] is DialogicTextEvent:
		if dialogic.current_timeline_events[index-1] is DialogicVoiceEvent:
			return true

	return false
```

**To Reproduce**
have a simple timeline:
![image](https://github.com/user-attachments/assets/e2e95ea8-5fea-47a8-b539-294b86a68bcd)

Invoking it in a script like:
`Dialogic.start("locked_door");`

Godot crashes with out of bounds error

**Expected behavior**
Dialogic should not crash Godot

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Windows, Linux]
 MacOs 14.5 (23F79)
 - Godot Version: [e.g. 4.2.2]
v4.2.2.stable.official [15073afe3]
 - Dialogic Version: [e.g. 2.0 Alpha 14, please be specific!]
2.0-Alpha-14 (Godot 4.2+)

**Comment by Jowan-Spooner** [comment]
I think this should not happen anymore in alpha 15. If you still experience this, feel free to reopen this issue.
