### ISSUE TITLE
Dialogic.Audio.base_music_player.volume_db = new value does not work anymore

### ISSUE THREAD

**Issue by gravit22** [dialogic-godot/dialogic#2361]
Dialogic.Audio.base_music_player.volume_db = new value used to work in previous version of dialogic, now it doesn't do anything. And I do not know how to adjust global music or sounds. 
Godot v4.2.2.stable - Ubuntu 22.04.4 LTS 22.04 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 3GB (nvidia; 535.183.01) - AMD Ryzen 9 3900X 12-Core Processor (24 Threads)
version="2.0-Alpha-15 WIP (Godot 4.2+)"

**Comment by Jowan-Spooner** [comment]
The correct way to adjust the volume it to adjust the volume of the Audio Bus that the music_player is on.
https://docs.godotengine.org/en/stable/tutorials/audio/audio_buses.html

Here is an explanation of how audio settings can be implemented: https://github.com/Jowan-Spooner/Dialogic2FantasyTemplate?tab=readme-ov-file#audio-settings

**Comment by gravit22** [comment]
Thank you. That solved the issue
