### ISSUE TITLE
The register_character() function doesn't work on an instance scene if that scene is called while another timeline is running.

### ISSUE THREAD

**Issue by Ziyuer97** [dialogic-godot/dialogic#2379]
### The Problem 

**Describe the bug**
The error `[ Invalid call. Nonexistent function 'register_character' in base 'CanvasLayer (default_layout_base.gd)'. ]` appears when I try to run a timeline using the Textbubble Style as an instance.

It runs normally if the timeline is executed without being an instance, or if no other timeline is running first.

Note that I have read a similar issue at > https://github.com/dialogic-godot/dialogic/issues/2193
However, even when I set the Textbubble Style as the default, it still doesn't work.

**To Reproduce:** 

I started by creating a base timeline using a VisualNovel Style. At some point, this "Base" timeline sends a signal to my "Main" script to instantiate a scene ("Sophia Chat.Tscn")  that runs another timeline called "Bubble Timeline" when the scene is instantiated. However, the "Bubble Timeline" scene cannot be executed because it fails to register the character "Bob."

**Screenshot**

![Screenshot 2024-08-28 085002](https://github.com/user-attachments/assets/e6ba9f31-420c-468c-8a96-193609c10c55)
![Screenshot 2024-08-28 085335](https://github.com/user-attachments/assets/43ca9487-f4b6-412a-84a7-4b02bc2aa6ee)
![Screenshot 2024-08-28 085615](https://github.com/user-attachments/assets/0180a9a4-5120-4143-963a-6c6983f11ec2)
![image](https://github.com/user-attachments/assets/83fb8abe-4959-457e-bdfe-42ae5f4d2b34)
![image](https://github.com/user-attachments/assets/4ed59ffe-1561-46d7-affb-aa71ec9e2119)

Below is the scene when I run it as an instance, but with no other timeline running.

![image](https://github.com/user-attachments/assets/d035699c-8f14-42b2-b7ac-68e4d50a052d)

**Expected Behavior**

I'm just starting to use Dialogic 2, so I don't fully understand what's wrong. What I want to do is have the "Base Timeline" trigger another scene to appear at some point, which will run the "Bubble" Timeline. Then, when the "Bubble" Timeline is over, it should return to the "Base Timeline" at the exact moment before the other scene was triggered.

Any help would be greatly appreciated.

**System**

OS: Windows
Godot Version: 4.2.1
Dialogic Version: 2.0 Alpha 14, downloaded most recent

**Comment by Jowan-Spooner** [comment]
I think this can be closed. The issue was resolved by properly loading the style before starting the timeline:
```
var layout = Dialogic.Styles.load_style("TextBubble_Style") # Use the name of the STYLE here
layout.register_character(...)
Dialogic.start("Timeline")
```
