### ISSUE TITLE
Game crashes after changing timeline

### ISSUE THREAD

**Issue by gravit22** [dialogic-godot/dialogic#2383]
without changing function to this, game crashes on changing timeline in some instances
```
## Finds the character node for a [param character].
## Return `null` if the [param character] is not part of the scene.
func get_character_node(character: DialogicCharacter) -> Node:
	if is_character_joined(character):
		var character_node = dialogic.current_state_info['portraits'][character.resource_path].node
		if is_instance_valid(character_node):
			return character_node

	return null
```
It's a quick fix, but hopefully it will be enough to understand the problem

**Comment by Jowan-Spooner** [comment]
@gravit22 please provide more info when opening issues: What dialogic version are you using, what godot version etc.
I'll have to assume you're using alpha 14, in which case this fix has already been made on the main branch.

**Comment by gravit22** [comment]
Version is 2.0-Alpha-15 WIP

**Comment by Jowan-Spooner** [comment]
Then it would be useful to get some information on the crash. Any error messages? I can't see a notable difference between the code you provided and what's currently on main, but maybe I'm missing something?

**Comment by gravit22** [comment]
Here is the screenshot of an error and previous code 
![image](https://github.com/user-attachments/assets/c6586773-485e-4a9e-97a1-f981e7ea74de)

**Comment by Jowan-Spooner** [comment]
Okay, yeah then this is an older version of alpha 15 WIP. This has been fixed on main already about two month ago. 
Thanks for the report! Really need to release alpha 15 now 🙈.
