### ISSUE TITLE
Character don't exit when called, on 4.3 Web Exports

### ISSUE THREAD

**Issue by metanoder** [dialogic-godot/dialogic#2384]
## The problem

**Describe the bug**
- On only web export, during dialogic play through, execute function "characters leave" 
- ( ie.. leave character1 [animation="Instant Out"] ) 
- No characters leave.

**To Reproduce**
- Functioning godot + dialogic project.
- Godot 4.3 web: threaded and single thread exports, on both prebuilt downloads and self compiled builds.
- Bug present in both exports.

**Expected behavior**
- Characters leave when called to.

**Screenshots**

**System (please complete the following information):**
 - OS: Windows and Mac
 - Godot Version: Godot 4.3 prebuilt and compiled
 - Dialogic Version: 2.0 Alpha 15

## Solutions
WIP

**Workaround**

Tried the different options for characters leaving.  
Leave --All--
Leave Character 1 
etc, nothing ran
<img width="367" alt="image" src="https://github.com/user-attachments/assets/dcea6ff8-316f-47a1-990c-2e1a48060f0b">

**Possible fixes**

Any idea to fix the issue or a link to the line of code that might be the cause for this problem

This might be a Godot Web Export Templates issue... as it works on other exports.  Will see if there's anything that can be done...

**Comment by Jowan-Spooner** [comment]
Hey @metanoder, thanks for the report. Could you check if #2391 fixes this for you? I confirmed that if fixes animations on a windows export and hoping it's the same issue.

**Comment by metanoder** [comment]
Hi @Jowan-Spooner 

Yes, that did it!
Tested on Godot 4.3 compiled single threaded and use the latest main dialogic build, and just typed in your fix. 
 
Ran it on Edge, Chrome, Firefox, and Safari.  
It works!

https://github.com/user-attachments/assets/5dbfb420-ffca-4776-bbae-cc38f3bddc41

thank you for the fix!
