### ISSUE TITLE
New 'pos' and 'size' features don't appear to work as intended

### ISSUE THREAD

**Issue by McStebb** [dialogic-godot/dialogic#2389]
## The problem

**Describe the bug**
Using 'pos' and 'size' on the same line as a character update causes character position to move in unintended ways.

**To Reproduce**
Using 'pos' and 'size' like this will cause the character portrait to size properly:
```
join Character pos=x0.7 y1.0
update Character size=y500px
```
This will cause the portrait to stay in the indicated position and change size, as intended.
![image](https://github.com/user-attachments/assets/4b77757a-4c02-4971-b750-5bc2e26a27b5)
![image](https://github.com/user-attachments/assets/013772cb-60af-47ad-b04f-2009e63ba1f0)

Using 'pos' and 'size' on the same line causes the portrait to jump up the screen:
```
join Character pos=x0.7 y1.0 size=y500px
update Character (Expression2)
```
![image](https://github.com/user-attachments/assets/edc08c9c-0d41-4382-bb64-b06ff4065d82)

...and then when `update` is called, the portrait snaps to the proper location.
![image](https://github.com/user-attachments/assets/6d3682ed-5168-429e-aa71-191273b63895)

**Expected behavior**
The portrait should remain in the correct screen position when a new scale is applied.

**Screenshots**
See above

**System (please complete the following information):**
 - OS: Windows 10
 - Godot Version: v4.3.stable.mono.official [77dcf97d8]
 - Dialogic Version: 2.0-Alpha-15

## Solutions

**Workaround**

Updating portrait scale and position separately allows the correct behavior, but with an uncomfortable gap of time, which causes the portrait to suddenly "snap" to the desired size after entering the scene.

**Comment by McStebb** [comment]
If I may tack on a feature request while this is being looked at ... 

Can the `pos` and `size` properties be tweened so that moving a character in real time is smooth and not jarring?

It's also possible they already are and  I'm using the commands wrong 😁

**Comment by Jowan-Spooner** [comment]
Hey @McStebb,
I've just made a PR (#2393) that should fix this. Would love if you could test it! Thanks.

**Comment by McStebb** [comment]
Sure! I'll take a look and let you know what I find later today.
