### ISSUE TITLE
"process_mode = Node.PROCESS_MODE_ALWAYS" doesn't perfectly worked when there is more than one style

### ISSUE THREAD

**Issue by ssw940521** [dialogic-godot/dialogic#2390]
## The problem

**Describe the bug**
here is my code:
```gdScript
func _run_interaction() -> void:
	Dialogic.process_mode = Node.PROCESS_MODE_ALWAYS
	get_tree().paused = true
	var dialouge = Dialogic.start("timeline")
	dialouge.process_mode = Node.PROCESS_MODE_ALWAYS
	await Dialogic.timeline_ended
	get_tree().paused = false
```

 I have two Style in my timeline , when the timeline started the text in the first style box can auto typing ,however the text in another style doesn't.And when I click mouse the timeline continues.

**Expected behavior**
the dialogue text auto typing should work

**Screenshots**
my style config:
![image](https://github.com/user-attachments/assets/07426ab5-a8d7-4eca-b3ea-7133aa97357d)
different character have different style:
![image](https://github.com/user-attachments/assets/8ea0f54e-33f5-449b-a736-43bfb5b4ee5e)
![image](https://github.com/user-attachments/assets/076479c7-cd2a-4823-b70c-1bf5052aacbf)
auto typing in first style:
![image](https://github.com/user-attachments/assets/7a44e017-2167-4cda-af9d-96e3156ecd83)

no auto typing in another style:
![image](https://github.com/user-attachments/assets/f9596cd8-bf13-4e0d-b25e-76cf22a4707a)

**System :**
 - OS: [Windows]
 - Godot Version: [ 4.3.stable]
 - Dialogic Version: [2.0 Alpha 15,]

**Comment by Jowan-Spooner** [comment]
Thanks for the report. This is expected, but I wanted to fix it before and have forgotten about it. I will take a stab at this soon.

**Comment by ssw940521** [comment]
> Thanks for the report. This is expected, but I wanted to fix it before and have forgotten about it. I will take a stab at this soon.

Thanks！
