### ISSUE TITLE
dialogic_default_action isn't respected by Centered Choices box

### ISSUE THREAD

**Issue by mak448a** [dialogic-godot/dialogic#2411]
## The problem

**Describe the bug**
`dialogic_default_action` isn't respected by Centered Choices box. So when I click on a button that I've assigned to this, it doesn't work.

**To Reproduce**
1. Assign a different button to `dialogic_default_action` in the Input Map. I used CTRL.
2. Make a timeline with centered choices.
3. Try to press ctrl to choose one.
4. It only works with the default buttons.

**Expected behavior**
It works with the new button.

**Screenshots**

**System (please complete the following information):**
 - OS: Fedora Linux 40 KDE Spin
 - Godot Version: 4.3
 - Dialogic Version: 2.0 Alpha 15

## Solutions

**Workaround**
You could probably send a space input action when ctrl is pressed?

**Possible fixes**

Not sure.

**Comment by Jowan-Spooner** [comment]
Choices are buttons and that means they use the ui_accept action not the advance action so this is expected. However I think we might be able to add a setting to also use the input action additionally to the ui_accept action.

**Comment by mak448a** [comment]
When I press advance it disables choosing anything for some reason.

**Comment by mak448a** [comment]
This is slightly off topic, but could you help me? I have a giant button over the whole screen that sends a dialogic default action event in the code. The choices lock up when I press it on the choice. 

Code: 
```gdscript
var dialog_advance_action_value: bool = true
func _on_button_button_down() -> void:
	print("Pressing dialogic_default_action...")
	# This one doesn't work. Use other way, as documented in action_press
	# docs. Input.action_press("dialogic_default_action")
	var action_dialog_proceed = InputEventAction.new()
	action_dialog_proceed.action = "dialogic_default_action"
	action_dialog_proceed.pressed = !dialog_advance_action_value
	Input.parse_input_event(action_dialog_proceed)
```

I assume that it's because I'm not freeing the dialog_advance_action_value by doing a key up? But I did it this way because the advance button gets broken otherwise.

**Comment by Jowan-Spooner** [comment]
What do you mean it freezes up the choices?

**Comment by mak448a** [comment]
They don't work anymore. But I do see it's on my end. Sorry!

**Comment by mak448a** [comment]
Should I close this issue since you can just rebind ui_accept?

**Comment by Jowan-Spooner** [comment]
@mak448a I think we can close this. You can now tell dialogic to use the default action for choices (in addition to the ui_accept action):
```gdscript
Dialogic.Choices.use_input_action = true
```
This is currently false by default and not exposed to the settings menu. If you feel like it should be, then let me know.

> Note: this setting only uses non-mouse based events from the input_action, because the advance action often includes left mouse button, and we don't want a click anywhere to select the focused choice.

**Comment by mak448a** [comment]
Could you add this to the docs? Thanks!
