### ISSUE TITLE
Fade Out Down doesn’t work on mobile

### ISSUE THREAD

**Issue by mak448a** [dialogic-godot/dialogic#2415]
## The problem

**Describe the bug**
Fade out down on a character doesn’t work on iOS. Instead, the character does nothing. Works before exporting.
My renderer is on compatibility.

**To Reproduce**
1. Make dialogic timeline with character. Join character. Add message. Leave character.2. 
2. Export to iOS and run.
3. See error.

**Expected behavior**
It works

**Screenshots**

**System (please complete the following information):**
 - OS: iOS (and Linux dev station)
 - Godot Version: 4.3
 - Dialogic Version: 2.0 Alpha 15

## Solutions

**Workaround**

not sure

**Possible fixes**

Not sure

**Comment by mak448a** [comment]
I tested it on Android too. Not working.

**Comment by Jowan-Spooner** [comment]
Animations were broken in exports in alpha 15. Could you please try with the main branch?

**Comment by mak448a** [comment]
Ok, got it. I'll try when I have time

**Comment by mak448a** [comment]
Works on latest main branch.
