### ISSUE TITLE
[Request]: Signal to destroy/remove textbox, characters, etc.

### ISSUE THREAD

**Issue by mak448a** [dialogic-godot/dialogic#2419]
**Is your feature request related to a problem? Please describe.**
I tried to do this manually with `get_parent().queue_free()` on a custom VN node, which does work if called right from the timeline before it ends, but not when called with a script during the timeline. Could you add a signal or something to emit to destroy the dialogic textbox and stuff so that it can load a new dialog?

**Describe the solution you'd like**
A signal or something to destroy the textbox and related stuff (characters, etc.)

**Describe alternatives you've considered**
Destroying them manually (which only works sometimes)

**Additional context**

**Comment by mak448a** [comment]
Also, one more thing: I could be doing something wrong. I probably am.

**Comment by mak448a** [comment]
Whoops never mind I got it

**Comment by Jowan-Spooner** [comment]
Not sure how you solved your problem, but `Dialogic.end_timeline()` or `Dialogic.Styles.get_layout_node().queue_free()` should both work.
