### ISSUE TITLE
Unable to select Typing Sound Audio Bus via Layer Settings

### ISSUE THREAD

**Issue by anis-mahsoume** [dialogic-godot/dialogic#2420]
I am not able to change the bus for the character typing sounds.

I have searched on the previous commits and found this one:
https://github.com/dialogic-godot/dialogic/pull/344/commits/e83d7e6a431d74e843c7c3e8458de29df5c20a99

Seems like there use to be a field to set the bus for typing sounds. is there an equivalent now ? I cannot find it in the documentation or in the issues neither.

**Comment by CakeVR** [comment]
Right now, the Layers having the Node with the Typing Sounds cannot be changed from the Layer Configuration. If you want, you are free to add such possibility to all built-in Dialogic Styles.

However, you can turn the Layer with the Typing Sounds Node into a *Custom Layer* and then simply change the Audio Bus on the Node. The Node is named `DialogicNode_TypeSounds`.

**Comment by anis-mahsoume** [comment]
Thanks @CakeVR  for your response. I have made a pull request to add the option into character settings:
#2425

**Comment by anis-mahsoume** [comment]
Hi @CakeVR, concerning my PR, since it's my first participation I am not aware of the process. Can I get it merged ?
