### ISSUE TITLE
Copying Multiple Items from one timeline to another sends the first item to the bottom of the ordering when pasted

### ISSUE THREAD

**Issue by adrientremblay** [dialogic-godot/dialogic#2455]
## The problem

**Describe the bug**
Copying Multiple Items from one timeline to another sends the first item to the bottom of the ordering when pasted

**To Reproduce**
1. Create a new timeline with multiple distinct items
2. Select all items and copy them to the clipboard
3. Create another timeline and paste the items into the timeline
4. Observe the first item in the original sequence is at the bottom

**Expected behavior**
The pasted items to maintain their ordering

**Screenshots**
N/A

**System (please complete the following information):**
 - OS: Linux
 - Godot Version: 4.3 Stable
 - Dialogic Version: Dialogic 2.0 - Alpha 15

## Solutions

**Workaround**

N/A

**Possible fixes**

N/A

**Comment by Jowan-Spooner** [comment]
I cannot recreate this on windows on the main branch. Could you share more about your setup, maybe a video, screenshots, etc.

**Comment by adrientremblay** [comment]
Heres a video of me producing the bug: https://youtu.be/TUHs4zfXs4o

I am on Linux Mint. Maybe this is a linux only issue? Wild Guess: but maybe there are some particularities to the linux clipboard.

**Comment by salianifo** [comment]
Confirmed. Happens on both Windows and Linux.

**Comment by Jowan-Spooner** [comment]
That makes sense, I wasn't pasting into an empty timeline, my bad for not following the steps precisely 🙈.

**Comment by adrientremblay** [comment]
Thanks guys!!!! @Jowan-Spooner @salianifo
