### ISSUE TITLE
Text Search in Timeline Editor

### ISSUE THREAD

**Issue by Taylor-Mattison** [dialogic-godot/dialogic#2466]
**Is your feature request related to a problem? Please describe.**
I can't search Dialogic Timeline files to easily navigate to certain dialog lines or events.

**Describe the solution you'd like**
I'd like to be able to open a Timeline in Dialogic and press Ctrl+F or navigate a menu to be able to search the timeline for matching text - similar to the find & replace feature available when editing GDScript files.

**Describe alternatives you've considered**
I've considered editing timelines in external text editors such as VS Code, but ran into strange behavior from Godot when trying to save changes.

**Additional context**
Example of the search menu when opening GDScript files in-editor:

![gdscript search](https://github.com/user-attachments/assets/1b285878-f3a7-45e7-a9d7-4c33b1625846)

**Comment by CakeVR** [comment]
Thanks for your request.

**Comment by Jowan-Spooner** [comment]
@Taylor-Mattison You absolutely CAN press CTRL+F to search in timelines. Please test the feature and then give feedback on how it could be improved if it still doesn't match your expectations.

**Comment by Taylor-Mattison** [comment]
Interesting! I updated my dialogic version from 2.0-Alpha-14 to 2.0-Alpha-16 and Ctrl-F works as intended. To sanity check, I also created brand new projects following the install instructions for 2.0-Alpha-14 and separately for 2.0-Alpha-16. In v14, search did not work; in v16 search did work.
Looks like v14 search is missing or broken, but v16 is working as intended.

**Comment by salianifo** [comment]
I looked at the commit history, and the search feature was implemented in alpha-15, so this makes sense.
