### ISSUE TITLE
Out of bounds get index '0' on Godot build

### ISSUE THREAD

**Issue by extra-large-onions** [dialogic-godot/dialogic#2468]
## The problem

**Describe the bug**
I'm trying to open a Dialogic dialogue when clicking on the player with Dialogic.start(), which works fine in dev, but doesn't in build
**To Reproduce**

**Expected behavior**
Dialogue is opened

**Screenshots**
- console error in build
  - ![Screenshot 2024-11-06 121211](https://github.com/user-attachments/assets/87a89d90-dbb9-47a8-a897-86ae6956f99a)
- works fine in dev
  - ![image](https://github.com/user-attachments/assets/2ae8a3f3-fd3b-4557-83b9-91e45bd2bfca)

- dialogic ( latest version)
  - ![image](https://github.com/user-attachments/assets/6ef215b8-0de9-4d04-a0b8-4411d5040891)
- character
  - ![image](https://github.com/user-attachments/assets/6d70b330-10b1-471e-8ad0-64e9986d1b26)

**System (please complete the following information):**
 - OS: Window
 - Godot Version: 4.3
 - Dialogic Version: 2.0 Alpha 16

## Solutions

**Workaround**
- So I thought it was a resource name change by godot, and download godot resource groups https://github.com/derkork/godot-resource-groups, but the problem is still there
- Also included .dtl and .dch in build paths
- removed cache folder .godot
- tried calling Dialogic.start with string, with resource
**Possible fixes**

**Comment by Jowan-Spooner** [comment]
Hey I wasn't able to reproduce it yet. However I'm curious about the "false" argument you give to Dialogic.start(). What exactly do you try to do there?

**Comment by extra-large-onions** [comment]
> Hey I wasn't able to reproduce it yet. However I'm curious about the "false" argument you give to Dialogic.start(). What exactly do you try to do there?
Ah, I think I copypasted that from somewhere else without actually knowing what it does.
I tried out Nathan's Dialogue Manager and got some sort of error as well, think it has something to do with the resource files (.dialogue in Dialogue Manager and .dtl in Dialogic) being empty on build. I'll probably try another computer or another Godot version, see if it helps. Thanks.

**Comment by bazsupport** [comment]
im getting the same thing with our project, works in editor but not on build:
![WindowsTerminal_Y6cbh8SBiu](https://github.com/user-attachments/assets/cbd082a9-b836-496e-9234-84bcc2285376)

**Comment by bazsupport** [comment]
@extra-large-onions @Jowan-Spooner 

this issue is caused when using v0.4 of Resource Groups, reverting to v0.3 lets exports with dialogic work again! 
ive [made a ticket to Resource Group github page](https://github.com/derkork/godot-resource-groups/issues/14) to see if there is a reason and what a good solution would be to make their plugin more stable, if you want to put in your 2cents feel free

**Comment by bazsupport** [comment]
Last update: derkork fix this with Resource Groups v0.4.1

GG
