### ISSUE TITLE
Bubble style error - nonexistent register_character function

### ISSUE THREAD

**Issue by carter472** [dialogic-godot/dialogic#2469]
## The problem

Getting the error - **[ Invalid call. Nonexistent function 'register_character' in base 'CanvasLayer (default_layout_base.gd)'. ]** when attempting to use the premade bubble style. I have not changed the settings of the style and have used it "out of the box". 

Have tried 2 suggested fixes that I could find online but to no avail. 

**Fix 1** - The first fix [suggested here](https://forum.godotengine.org/t/dialogic-style-help/90016/2) was to make sure that the bubble style was the default style by clicking the star icon in the Styles tab and making sure BubbleStyle was yellow. I've checked this to be the case but got the same error. I then created a second style (BubbleStyle2) just to make sure there were 2 styles and BubbleStyle was the default (yellow). Again, same error. 

![image](https://github.com/user-attachments/assets/b392f4b5-9c58-483f-863c-00450a84146f)

**Fix 2** - Load the style before starting the timeline [suggested here](https://github.com/dialogic-godot/dialogic/issues/2379). 
![image](https://github.com/user-attachments/assets/efe74168-fc9e-474d-8480-355a85cccaa8)

To confirm, BubbleStyle has been added to the character that's supposed to use it
![image](https://github.com/user-attachments/assets/e4dec47c-716b-4207-9216-7699e0cc1930)

Can't find any other suggestions anywhere on how to resolve this issue. Can anyone help?

**To Reproduce**
1. Go to Styles and create the premade "TextBubble" style - save it as BubbleStyle
2. Assign the newly created BubbleStyle to a character and create a timeline with at least 1 text in it. 
3. Add any random 2D node and attach a script that'll allow you to run the Dialogic timeline. Code is as follows:

```
var layout = Dialogic.Styles.load_style("BubbleStyle")
layout.register_character(load("res://Common/Dialogic/Characters/player.dch"), $"../Player")
Dialogic.start("customer_queue_too_long")
```
4. This results in the error as outlined above and in red in the screenshot above. 

Alternative 1 - running it with the following code simply does nothing, which is odd because in minute 34:19 of [this video](https://www.youtube.com/watch?v=Tmy1tzhDLl4&list=PL3CSxZKz4Xi2z7fvLmqf7nCrEQ561Kod_&index=17&t=1001s), something at least happened and the text bubble still popped up
`Dialogic.start("customer_queue_too_long")`

Alternative 2 - running it with the following code results in the same error outlined above
```
var layout = Dialogic.start("customer_queue_too_long")
layout.register_character(load("res://Common/Dialogic/Characters/player.dch"), $"../Player"
```

**Expected behavior**
The bubble text to pop up above the player's head with the text as defined in the timeline. As can be seen in minute 1:45 of [this video](https://www.youtube.com/watch?v=WTeDyV_Yr-I) or minute 35:15 of [this video](https://www.youtube.com/watch?v=Tmy1tzhDLl4&list=PL3CSxZKz4Xi2z7fvLmqf7nCrEQ561Kod_&index=17&t=1001s)

**Screenshots**
Additional screenshots of my timeline
![image](https://github.com/user-attachments/assets/a58b6533-c1aa-46f3-a0eb-a6fa89707d19)

**System
 - OS: Windows
 - Godot Version: 4.3
 - Dialogic Version: 2.0 Alpha 16

**Comment by allendawodu** [comment]
Can confirm, Alpha 16 broke text bubbles for me as well. I had to downgrade to Alpha 15.

**Comment by marianasalimena** [comment]
Also having the same problem, tried to downgrade to Alpha 15 but it seems to continue with same error

**Comment by Jowan-Spooner** [comment]
I can confirm this. It can be fixed by manually replacing the base layer of the textbubble style with a real textbubble base layer:
![grafik](https://github.com/user-attachments/assets/1a1457a3-041e-46da-8f55-6e12ff5fabae)
![grafik](https://github.com/user-attachments/assets/47a4bc09-3d70-421f-87e0-6c147c98133b)

I'll try to fix this asap.
