### ISSUE TITLE
Got 1200-1500 errors when importing

### ISSUE THREAD

**Issue by Demperor212** [dialogic-godot/dialogic#2475]
## Can't import Dialogic 2

**Describe the bug**
In Godot v4.2.2 and 4.3, when I try to import Dialogic 2 Alpha 16, 15, 13 into the project, I would get 1200-1500 errors and the addon is not showing up in the project.

**To Reproduce**
Use the steps described in the installation tutorial to reproduce it.

**Expected behavior**
You get 1200-1500 errors

**Screenshots**
![Dialogic problem 2](https://github.com/user-attachments/assets/12a72ff8-ff4d-40a1-bb9d-1ecc3e5f621d)
]

**System (please complete the following information):**
 - OS: [Windows]
 - Godot Version: [4.2.2, 4.3 stable]

 - Dialogic Version: [2.0 Alpha 16, 15, 13]

## Solutions
Only once it worked in an empty 4.2.2 file,(with only 65 errors about missing texture) but I can not reproduce it.

**Workaround**
I tried two different versions of Godot and three different versions of Dialogic.

**Possible fixes**
Unfortunately, I don't know. If you also encounter this, try import it into an empty file (not always work)

**Comment by CakeVR** [comment]
Looking at your screenshots, you have not installed Dialogic correctly.

Please follow the instructions in our Docs: https://docs.dialogic.pro/getting-started.html#1-installation--activation

**Comment by CakeVR** [comment]
Nice to hear it works now.

It works just fine for users installing Dialogic 2 for Godot 4.3.
