### ISSUE TITLE
Audio Cues for other events

### ISSUE THREAD

**Issue by loansharkmann** [dialogic-godot/dialogic#384]
One of the problems I've faced when using Dialogic is the task of having to set up audio events that play once during certain events, like a character portrait introduction/change, or unique sounds for each dialog box. Something like [OFF](https://youtu.be/qh5P9JUMIdc?t=1140) is what I had in mind for this.

**Comment by Jowan-Spooner** [comment]
Hey @loansharkmann, I think there is already a dialog sound per character planned, which could help for your idea.

I think it will be very hard to figure out a clean UI for adding sound options to other events. Of course you can just use a Sound Event when a character enters. Also you could listen to the "event_start" signal of the dialog node. You could check the type of event and even it's specifics (like what player entered) and then play a sound or do whatever you want. It requires a bit more understanding of godot, gdscript and dialogic though.

If this is what you were looking for and you need some help, we are available on emilios discord server.

**Comment by loansharkmann** [comment]
Well, I was using Audio Events for it, but there were some delays between the portraits showing up and the audio being played, so I wanted to know if a more streamlined way of doing it would be possible. Anyway, thanks!

**Comment by coppolaemilio** [comment]
It would be interesting to make it easier to add sound to events being executed. Events like character join, close dialog, open dialog should all be easy to hookup with sounds. Maybe if we properly emit signals once those events are present we can write a small guide to how to write a global script to handle those sounds. Leaving the issue open to not forget about this one.
