### ISSUE TITLE
Save state loading broken in 1.4-dev when theme speed is set to 0

### ISSUE THREAD

**Issue by exelia-antonov** [dialogic-godot/dialogic#769]
**Describe the bug**
Something with the new DialogNode state machine, which I haven't been able to figure out myself to try and submit a fix, makes loading a save state put it into a state where it cannot be continued if the speed is set to 0, the next indicator never appears and does not respond to inputs. 

This only occurs if the speed is set to 0 _and_ a dialogue node is what is saved as the event it loads on, so if the speed for the theme is higher than 0 it acts normally (as it progresses through TYPING state and does that), or if the saved event is some other type of an event (such as a pause or a choice menu) then it acts normally

**To Reproduce**
1. have a save that was saved on a DialogNode
2. have a theme with speed set to 0
3. try and load the save

Screenshots comparing 1.3 and 1.4-dev, visually you can see the next indicator is not present on load:
![unknown (2)](https://user-images.githubusercontent.com/2214793/152685363-54e3ea09-e34e-4844-8900-0ada02759eca.png)

**Comment by thebardsrc** [comment]
The changes in PR #715 appear to have fixed the major problem, where it would not respond to input events to move on. The visual bug of the indicator not being there remains, but I would consider that cosmetic only and minor, so can wait for any later 1.4.x bugfixes

**Comment by coppolaemilio** [comment]
@exelia-antonov is this still a thing? If it is, feel free to reopen, otherwise I'll close since it is a 1.x issue and there isn't too much interest in it lately.
