### ISSUE TITLE
Improve using values in Condition and SetValue

### ISSUE THREAD

**Issue by Jowan-Spooner** [dialogic-godot/dialogic#803]
In both SetValue and Condition I think you are supposed to be able to use [Values] to add or compare values. 
This seems to not work as expected. Not sure if it's just not implemented. 

I will test this further in the future and update this report.

**Comment by Jowan-Spooner** [comment]
Will work on this now.

**Comment by Jowan-Spooner** [comment]
Alright, looked at it a bit more. It's not as broken as I thought, but not ideal nontheless
**Right now** 
- in the Condition event you have to enter the name of the value definition without brackets
  - this means if you have a value named "something" you cannot compare to the string "something"
- there is no way to use the path in the Condition event
  - this means if you have multiple value named "something" you cannot specify to which you want to compare 
- in the SetValue event, using values is just not supported

**I think I would like**
- people to have to specify whether they use a value or a string
   - this could be by enclosing the value with square brackets or by enabeling a selector with a toggle button
- to make specifying a specific value possible
   - either by making the use of full paths possible or by adding a selector (and thus using the ids instead of the names)
- to add similar ability to the SetValue event

Tell me what you think, and I can try to implement my suggestions

**Comment by coppolaemilio** [comment]
Hmm maybe using the full path can work? I'm thinking what it would make more sense for a Godot user to do but not really compromising the novice experience.

Feel free to implement it as you would like it to be 👍🏻
