### ISSUE TITLE
Use _unhandled_input() instead of _input() so not every click advances dialog

### ISSUE THREAD

**Issue by Jowan-Spooner** [dialogic-godot/dialogic#827]
**Is your feature request related to a problem? Please describe.**
In the VN template I noticed that clicking on one of the buttons always also advances the dialog. Even get_tree().set_input_as_handled() does nothing, because the dialog node doesn't care for that. 

**Describe the solution you'd like**
Make the DialogNode use _unhandled_input() or make it possible through different means to have certain clicks (like those on buttons) NOT advance the dialog.

**Comment by hicchanwan** [comment]
I have created a temporary solution for this case.. go to the *Text file Bubbles.gd *, find the line func skip(): and create
var click = 0 over it and rewrite the function itself to 
func skip():
if click == 1:
text_label.visible_characters = -1
_handle_text_completed()
yield(get_tree().create_timer(0.7),"timeout")
click = 0

this will help to remove unnecessary pressing by artificially slowing down the passes

**Comment by coppolaemilio** [comment]
@Jowan-Spooner is this also happening in 2.0?

**Comment by zaknafean** [comment]
This does not appear to be an issue in Dialogic 2 given the input sub system and the splitting of mouse input and all other input within that. I'm closing this to clear it out.
