### ISSUE TITLE
Custom pixel font is being cut off on the bottom line

### ISSUE THREAD

**Issue by LeonStansfield** [dialogic-godot/dialogic#941]
## The problem

**Describe the bug**
My custom pixel font is being cut off on the bottom line. It is asif the bottom pixel of the font is not being rendered properly. This only happens to the bottom line of the dialogue

**To Reproduce**
1. Create a new theme
2. use a low pixel count (eg 16 pixel tall) font as your regular font
3. See error

**Expected behavior**
Font should be displayed properly without cutting off the bottom.

**Screenshots**
![image](https://user-images.githubusercontent.com/23266792/175782376-3cc23d4a-f57f-4e44-8a70-ded76fc85606.png)

**System (please complete the following information):**
 - OS: Windows 11
 - Godot Version: 3.4
 - Dialogic Version: 1.4.1

## Solutions

**Workaround**

Scaling up the font to be larger. This takes a lot of time, especially with custom fonts.

**Possible fixes**

Any idea to fix the issue or a link to the line of code that might be the cause for this problem

**Comment by zaknafean** [comment]
Going to close this one up, as I can't really recreate this in 1.5.x.

In general given the limitations of Label in Godot 3, there is only so much the tool can do with this. You really just have to build your font and style box around the limits.
