### ISSUE TITLE
Plugin translation [ Arabic ]

### ISSUE THREAD

**Issue by theVoidZ** [dialogic-godot/dialogic#989]
Since Godot does not support Arabic yet. i ll open an issue for Translating the plugin to Arabic. 
90%+ of the entries are translated. 
- Translation File. [dialogic.csv](https://github.com/coppolaemilio/dialogic/files/9071032/dialogic.csv)

**Comment by coppolaemilio** [comment]
Thank you so much! I'll let you know when we are ready with Dialogic for Godot 2 and we can integrate your translation! 

شكرا لك

**Comment by CakeVR** [comment]
As this is now almost two years old, I will close this.

The issue #1534 exists, future endeavours should be discussed this. It's a lot of work to translate the editor and I think `gettext` may be more suited for this than CSV.
