### ISSUE TITLE
Plugin translation [ French ] - Updated

### ISSUE THREAD

**Issue by theVoidZ** [dialogic-godot/dialogic#991]
Translation of the Plugin in French ( Updated and completed the missing entries )
90%+ of the entries are translated.
- Translation File [dialogic.csv](https://github.com/coppolaemilio/dialogic/files/9072353/dialogic.csv)

**Comment by CakeVR** [comment]
As this is now almost two years old, I will close this.

The issue #1534 exists, future endeavours should be discussed this. It's a lot of work to translate the editor and I think `gettext` may be more suited for this than CSV.
